### ISSUE TITLE
Error: The requested accessory 'xioamifan' was not registered by any plugin.

### ISSUE THREAD

**Issue by DJay-X** [merdok/homebridge-xiaomi-fan#1]
@merdok First of all, thanks for your work and sharing.

I am using my Smartmi Fan (ZRFFS01ZM) with Battery, Natural wind, White stand (not sure what the exact model is) with the https://github.com/YinHangCode/homebridge-mi-fan since many moth now.
But of course I would love to give your plugin a chance and see if it is a perfect replacement for the old plugin.

Unfortunately I did not get it to work. Any Idea?
I am running several plugins on my Pi 3 B+. 
homebridge@0.4.50 | node@11.14.0 | npm 6.10.3 | n@5.0.1 | miio@0.15.6

```
        {
            "accessory": "xiaomifan",
            "name": "Xiaomi Fan",
            "ip": "xxx.xxx.xxx.xx",
            "token": "12a356b7c8d2b89e12fgh1i3j45kl67m",
            "pollingInterval": 5,
            "moveControl": true,
            "buzzerControl": true,
            "ledControl": true
        }
```

```
[Aug 11 18:24:53 raspberrypi-3BPlus homebridge[2724]: [2019-8-11 18:24:53] Loaded plugin: homebridge-xiaomi-fan
Aug 11 18:24:53 raspberrypi-3BPlus homebridge[2724]: [2019-8-11 18:24:53] Registering accessory 'homebridge-xiaomi-fan.xiaomifan'

Aug 11 18:24:57 raspberrypi-3BPlus homebridge[2724]: [2019-8-11 18:24:57] Error: The requested accessory 'xiaomifan' was not registered by any plugin.
Aug 11 18:24:57 raspberrypi-3BPlus homebridge[2724]:     at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:64:13)
Aug 11 18:24:57 raspberrypi-3BPlus homebridge[2724]:     at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:297:42)
Aug 11 18:24:57 raspberrypi-3BPlus homebridge[2724]:     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:91:38)
Aug 11 18:24:57 raspberrypi-3BPlus homebridge[2724]:     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
Aug 11 18:24:57 raspberrypi-3BPlus homebridge[2724]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Aug 11 18:24:57 raspberrypi-3BPlus homebridge[2724]:     at Module._compile (internal/modules/cjs/loader.js:816:30)
Aug 11 18:24:57 raspberrypi-3BPlus homebridge[2724]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
Aug 11 18:24:57 raspberrypi-3BPlus homebridge[2724]:     at Module.load (internal/modules/cjs/loader.js:685:32)
Aug 11 18:24:57 raspberrypi-3BPlus homebridge[2724]:     at Function.Module._load (internal/modules/cjs/loader.js:620:12)
Aug 11 18:24:57 raspberrypi-3BPlus homebridge[2724]:     at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Aug 11 18:24:57 raspberrypi-3BPlus homebridge[2724]:     at internal/main/run_main_module.js:21:11](url)
```

**Comment by DJay-X** [comment]
There was a mishmash with the Name in the readme.
xioamifan
      "accessory": "xioamifan",

copy/paste miss.

Should be "xiaomifan"
