### ISSUE TITLE
HomeKit not working (Plug-in generates characteristic warning)

### ISSUE THREAD

**Issue by bittsii** [merdok/homebridge-xiaomi-fan#104]
Good Afternoon!
For some time now the plug-in is not working as expected and controls in the home app are not working as well (connection issue). 
min the log file of homebridge I always get errors for characteristic warnings, being „unknown“ for temperature and humidity. 

does anyone else have this problem?

Thanks!

**Comment by merdok** [comment]
Hi,
you would need to provide homebridge debug log, your config and the exact device which you are trying to control. Without that no real help cannot be given...

**Comment by bittsii** [comment]
Hi, 

That’s a good point, sorry for that.. I can already share config + device info, will update log later, when I return home. 

Device are 

zhimi.fan.za4 (Smartmi Standing Fan 2S)
zhimi.fan.za5 (Smartmi Standing Fan 3)


Config:

            "devices": [
                {
                    "name": "Xiaomi Smartmi Fan 3",
                    "ip": "192.168.178.33",
                    "token": "4f85a283f….",
                    "pollingInterval": 5,
                    "buzzerControl": true,
                    "ledControl": true,
                    "naturalModeControl": true,
                    "sleepModeControl": true,
                    "moveControl": true,
                    "shutdownTimer": false,
                    "angleButtons": [
                        30
                    ],
                    "ioniserControl": true
                },
                {
                    "name": "Xiaomi Smartmi Fan 2S",
                    "ip": "192.168.178.50",
                    "token": "45d4070b…",
                    "pollingInterval": 5,
                    "buzzerControl": true,
                    "ledControl": true,
                    "naturalModeControl": true,
                    "sleepModeControl": true,
                    "moveControl": true,
                    "shutdownTimer": false,
                    "angleButtons": [
                        0
                    ],
                    "ioniserControl": false
                }
            ],
            "platform": "xiaomifan"
        },
        {

**Comment by merdok** [comment]
Config look ok, please post the debug log when you can later!

**Comment by entoryFB** [comment]
I have the same problem for 4 Weeks

Debug log

[xiaomifan] [My Xiaomi Fan] Connected to Fan zhimi.fan.za4
[2021-7-26 15:01:49] [xiaomifan] [My Xiaomi Fan] Setting up fan!
[2021-7-26 15:01:49] [xiaomifan] [My Xiaomi Fan] Getting device info.
[2021-7-26 15:01:49] [xiaomifan] [My Xiaomi Fan] Doing model specific setup.
[2021-7-26 15:01:49] [xiaomifan] [My Xiaomi Fan] Adding properties to fan.
[2021-7-26 15:01:49] [xiaomifan] [My Xiaomi Fan] Doing initial properties fetch.
[2021-7-26 15:01:49] [xiaomifan] [My Xiaomi Fan] Setup finished! Fan can now be controlled!
[2021-7-26 15:01:49] [xiaomifan] [My Xiaomi Fan] Successfully saved fan info!

[xiaomifan] [My Xiaomi Fan] Error while setting property power to value true! Error: busy.
[2021-7-26 15:02:01] [xiaomifan] [My Xiaomi Fan] Error on initial property request! Error: Call to device timed out
[2021-7-26 15:02:02] [xiaomifan] [My Xiaomi Fan] Poll failed! No response from Fan! Stopping polling! Error: Error: busy.
[2021-7-26 15:02:02] [xiaomifan] [My Xiaomi Fan] Trying to reconnect
[2021-7-26 15:02:02] [xiaomifan] [My Xiaomi Fan] Error while setting property fan_speed to value 100! Error: busy.
[2021-7-26 15:02:02] [xiaomifan] [My Xiaomi Fan] Error: Could not connect to device, token might be wrong
[2021-7-26 15:02:02] [xiaomifan] [My Xiaomi Fan] Could not connect to the fan! Retrying in 36 seconds!
[2021-7-26 15:02:02] [xiaomifan] [My Xiaomi Fan] Error while setting property power to value true! Error: Network communication is unavailable, device might be destroyed
[2021-7-26 15:02:02] [xiaomifan] [My Xiaomi Fan] Error while setting property fan_speed to value 66! Error: Network communication is unavailable, device might be destroyed

**Comment by merdok** [comment]
@entoryFB in your case it looks like a network issue. The communication to the device seems to be very slow. Check your network or try to increase the polling interval to a higher value to reduce the load on the device.

**Comment by bittsii** [comment]
I think I get a quite similar response, hope this is the correct log. The setup worked quite well before with no change on the network. 
I also can control the fan outside of HomeKit and it is working (not destroyed ;))

you can ignore the 2S one, as the battery is dead. 

Starting to advertise 'Homebridge 7D9F F28C' using ciao backend!
[7/26/2021, 7:10:15 PM] Homebridge v1.3.4 (Homebridge 7D9F) is running on port 51313.
[7/26/2021, 7:10:16 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Connected to Fan zhimi.fan.za5
[7/26/2021, 7:10:16 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Setting up fan!
[7/26/2021, 7:10:16 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Getting device info.
[7/26/2021, 7:10:16 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Got fan did: 307560845.
[7/26/2021, 7:10:16 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Doing model specific setup.
[7/26/2021, 7:10:16 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Adding properties to fan.
[7/26/2021, 7:10:16 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Doing initial properties fetch.
[7/26/2021, 7:10:16 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Setup finished! Fan can now be controlled!
[7/26/2021, 7:10:16 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Successfully saved fan info!
[7/26/2021, 7:10:17 PM] [xiaomifan] [Xiaomi Smartmi Fan 2S] Error: Could not connect to device, handshake timeout
[7/26/2021, 7:10:17 PM] [xiaomifan] [Xiaomi Smartmi Fan 2S] Could not connect to the fan! Retrying in 30 seconds!
[7/26/2021, 7:10:28 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Error on initial property request! Error: Call to device timed out
[7/26/2021, 7:10:33 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Poll failed! No response from Fan! Stopping polling! Error: Error: Call to device timed out
[7/26/2021, 7:10:33 PM] [homebridge-xiaomi-fan] This plugin generated a warning from the characteristic 'Current Temperature': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[7/26/2021, 7:10:33 PM] [homebridge-xiaomi-fan] Error: 
    at CurrentTemperature.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at CurrentTemperature.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1931:16)
    at CurrentTemperature.Characteristic.updateValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1379:20)
    at xiaomiFanDevice.updateFanStatus (/usr/local/lib/node_modules/homebridge-xiaomi-fan/index.js:952:113)
    at FanController.<anonymous> (/usr/local/lib/node_modules/homebridge-xiaomi-fan/index.js:142:12)
    at FanController.emit (events.js:315:20)
    at /usr/local/lib/node_modules/homebridge-xiaomi-fan/lib/FanController.js:97:16
[7/26/2021, 7:10:33 PM] [homebridge-xiaomi-fan] This plugin generated a warning from the characteristic 'Current Relative Humidity': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[7/26/2021, 7:10:33 PM] [homebridge-xiaomi-fan] Error: 
    at CurrentRelativeHumidity.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at CurrentRelativeHumidity.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1931:16)
    at CurrentRelativeHumidity.Characteristic.updateValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1379:20)
    at xiaomiFanDevice.updateFanStatus (/usr/local/lib/node_modules/homebridge-xiaomi-fan/index.js:953:128)
    at FanController.<anonymous> (/usr/local/lib/node_modules/homebridge-xiaomi-fan/index.js:142:12)
    at FanController.emit (events.js:315:20)
    at /usr/local/lib/node_modules/homebridge-xiaomi-fan/lib/FanController.js:97:16
[7/26/2021, 7:10:33 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Trying to reconnect
[7/26/2021, 7:10:33 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Connected to Fan zhimi.fan.za5
[7/26/2021, 7:10:33 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Setting up fan!
[7/26/2021, 7:10:33 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Getting device info.
[7/26/2021, 7:10:33 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Doing model specific setup.
[7/26/2021, 7:10:33 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Adding properties to fan.
[7/26/2021, 7:10:33 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Doing initial properties fetch.
[7/26/2021, 7:10:33 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Setup finished! Fan can now be controlled!
[7/26/2021, 7:10:33 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Successfully saved fan info!
[7/26/2021, 7:10:38 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Poll failed! No response from Fan! Stopping polling! Error: Error: Call to device timed out
[7/26/2021, 7:10:38 PM] [homebridge-xiaomi-fan] This plugin generated a warning from the characteristic 'Current Temperature': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[7/26/2021, 7:10:38 PM] [homebridge-xiaomi-fan] Error: 
    at CurrentTemperature.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at CurrentTemperature.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1931:16)
    at CurrentTemperature.Characteristic.updateValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1379:20)
    at xiaomiFanDevice.updateFanStatus (/usr/local/lib/node_modules/homebridge-xiaomi-fan/index.js:952:113)
    at FanController.<anonymous> (/usr/local/lib/node_modules/homebridge-xiaomi-fan/index.js:142:12)
    at FanController.emit (events.js:315:20)
    at /usr/local/lib/node_modules/homebridge-xiaomi-fan/lib/FanController.js:97:16
[7/26/2021, 7:10:38 PM] [homebridge-xiaomi-fan] This plugin generated a warning from the characteristic 'Current Relative Humidity': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[7/26/2021, 7:10:38 PM] [homebridge-xiaomi-fan] Error: 
    at CurrentRelativeHumidity.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at CurrentRelativeHumidity.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1931:16)
    at CurrentRelativeHumidity.Characteristic.updateValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1379:20)
    at xiaomiFanDevice.updateFanStatus (/usr/local/lib/node_modules/homebridge-xiaomi-fan/index.js:953:128)
    at FanController.<anonymous> (/usr/local/lib/node_modules/homebridge-xiaomi-fan/index.js:142:12)
    at FanController.emit (events.js:315:20)
    at /usr/local/lib/node_modules/homebridge-xiaomi-fan/lib/FanController.js:97:16
[7/26/2021, 7:10:38 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Trying to reconnect
[7/26/2021, 7:10:38 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Error: Could not connect to device, token might be wrong
[7/26/2021, 7:10:38 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Could not connect to the fan! Retrying in 30 seconds!
[7/26/2021, 7:10:39 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Error on initial property request! Error: Network communication is unavailable, device might be destroyed
[7/26/2021, 7:10:49 PM] [xiaomifan] [Xiaomi Smartmi Fan 2S] Error: Could not connect to device, handshake timeout
[7/26/2021, 7:10:49 PM] [xiaomifan] [Xiaomi Smartmi Fan 2S] Could not connect to the fan! Retrying in 30 seconds!
[7/26/2021, 7:11:08 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Connected to Fan zhimi.fan.za5
[7/26/2021, 7:11:08 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Setting up fan!
[7/26/2021, 7:11:08 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Getting device info.
[7/26/2021, 7:11:08 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Doing model specific setup.
[7/26/2021, 7:11:08 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Adding properties to fan.
[7/26/2021, 7:11:08 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Doing initial properties fetch.
[7/26/2021, 7:11:08 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Setup finished! Fan can now be controlled!
[7/26/2021, 7:11:08 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Successfully saved fan info!
[7/26/2021, 7:11:20 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Error on initial property request! Error: Call to device timed out
[7/26/2021, 7:11:21 PM] [xiaomifan] [Xiaomi Smartmi Fan 2S] Error: Could not connect to device, handshake timeout
[7/26/2021, 7:11:21 PM] [xiaomifan] [Xiaomi Smartmi Fan 2S] Could not connect to the fan! Retrying in 30 seconds!
[7/26/2021, 7:11:25 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Poll failed! No response from Fan! Stopping polling! Error: Error: Call to device timed out
[7/26/2021, 7:11:25 PM] [homebridge-xiaomi-fan] This plugin generated a warning from the characteristic 'Current Temperature': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[7/26/2021, 7:11:25 PM] [homebridge-xiaomi-fan] Error: 
    at CurrentTemperature.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at CurrentTemperature.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1931:16)
    at CurrentTemperature.Characteristic.updateValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1379:20)
    at xiaomiFanDevice.updateFanStatus (/usr/local/lib/node_modules/homebridge-xiaomi-fan/index.js:952:113)
    at FanController.<anonymous> (/usr/local/lib/node_modules/homebridge-xiaomi-fan/index.js:142:12)
    at FanController.emit (events.js:315:20)
    at /usr/local/lib/node_modules/homebridge-xiaomi-fan/lib/FanController.js:97:16
[7/26/2021, 7:11:25 PM] [homebridge-xiaomi-fan] This plugin generated a warning from the characteristic 'Current Relative Humidity': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[7/26/2021, 7:11:25 PM] [homebridge-xiaomi-fan] Error: 
    at CurrentRelativeHumidity.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at CurrentRelativeHumidity.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1931:16)
    at CurrentRelativeHumidity.Characteristic.updateValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1379:20)
    at xiaomiFanDevice.updateFanStatus (/usr/local/lib/node_modules/homebridge-xiaomi-fan/index.js:953:128)
    at FanController.<anonymous> (/usr/local/lib/node_modules/homebridge-xiaomi-fan/index.js:142:12)
    at FanController.emit (events.js:315:20)
    at /usr/local/lib/node_modules/homebridge-xiaomi-fan/lib/FanController.js:97:16
[7/26/2021, 7:11:25 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Trying to reconnect
[7/26/2021, 7:11:26 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Connected to Fan zhimi.fan.za5
[7/26/2021, 7:11:26 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Setting up fan!
[7/26/2021, 7:11:26 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Getting device info.
[7/26/2021, 7:11:26 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Doing model specific setup.
[7/26/2021, 7:11:26 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Adding properties to fan.
[7/26/2021, 7:11:26 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Doing initial properties fetch.
[7/26/2021, 7:11:26 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Setup finished! Fan can now be controlled!
[7/26/2021, 7:11:26 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Successfully saved fan info! Nacho

**Comment by merdok** [comment]
@bittsii I would guess that this is a network issue on your side, you could try to to set a higher polling interval to reduce the load on the device.

**Comment by bittsii** [comment]
I doubt this be the problem. I am using the newest flagship FRITZ!Box, have low workload on both, the box and the network and all other equipment is working as expected. 
I also reconnected the 2S and it is working just fine (like the 3 did before) and also getting the config

[7/26/2021, 11:21:23 PM] [xiaomifan] [Xiaomi Smartmi Fan 2S] Connected to Fan zhimi.fan.za4
[7/26/2021, 11:21:23 PM] [xiaomifan] [Xiaomi Smartmi Fan 2S] Setting up fan!
[7/26/2021, 11:21:23 PM] [xiaomifan] [Xiaomi Smartmi Fan 2S] Getting device info.
[7/26/2021, 11:21:23 PM] [xiaomifan] [Xiaomi Smartmi Fan 2S] Got fan did: 106793298.
[7/26/2021, 11:21:23 PM] [xiaomifan] [Xiaomi Smartmi Fan 2S] Doing model specific setup.
[7/26/2021, 11:21:23 PM] [xiaomifan] [Xiaomi Smartmi Fan 2S] Adding properties to fan.
[7/26/2021, 11:21:23 PM] [xiaomifan] [Xiaomi Smartmi Fan 2S] Doing initial properties fetch.
[7/26/2021, 11:21:23 PM] [xiaomifan] [Xiaomi Smartmi Fan 2S] Setup finished! Fan can now be controlled!
[7/26/2021, 11:21:23 PM] [xiaomifan] [Xiaomi Smartmi Fan 2S] Successfully saved fan info!
[7/26/2021, 11:21:23 PM] [xiaomifan] [Xiaomi Smartmi Fan 2S] Got initial fan properties: 
 {
  "angle": 90,
  "speed": 0,
  "poweroff_time": 0,
  "power": "off",
  "ac_power": "on",
  "angle_enable": "off",
  "speed_level": 42,
  "natural_level": 42,
  "child_lock": "off",
  "buzzer": 0,
  "led_b": 0,
  "use_time": 55020
}

On the other hand for the 3 it is saying 


[7/26/2021, 11:21:55 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Connected to Fan zhimi.fan.za5
[7/26/2021, 11:21:55 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Setting up fan!
[7/26/2021, 11:21:55 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Getting device info.
[7/26/2021, 11:21:55 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Doing model specific setup.
[7/26/2021, 11:21:55 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Adding properties to fan.
[7/26/2021, 11:21:55 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Doing initial properties fetch.
[7/26/2021, 11:21:55 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Setup finished! Fan can now be controlled!
[7/26/2021, 11:21:55 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Successfully saved fan info!
[7/26/2021, 11:21:57 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Error on initial property request! Error: Call to device timed out
[7/26/2021, 11:22:07 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Error on initial property request! Error: Call to device timed out
[7/26/2021, 11:22:17 PM] [xiaomifan] [Xiaomi Smartmi Fan 3] Poll failed! No response from Fan! Stopping polling! Error: Error: Call to device timed out

The device is shown in the home app, I also can use Switches but it just isn’t doing anything.

**Comment by bittsii** [comment]
PS: Also switched polling to 10, 15 or 20 and did not change nothing.

**Comment by merdok** [comment]
@bittsii your issue has nothing to do with this plugin. I do not know if it is caused by your network or something else in your environment, but you would need to investigate it and find the cause. The error clearly states `Call to device timed out`, this basically means that the device cannot be reached in the network...

**Comment by entoryFB** [comment]
I have now set the interval high, but there is no change. The fan reacts immediately in the APP. just not about Homebridge. That always worked great until the last update. So I don't think it's the network. Unfortunately, the plug-in is no longer usable for me. Pity

**Comment by merdok** [comment]
@entoryFB again, it has nothing to do with the plugin but with your local network. The mi home app still works because it is using the cloud for communication instead of the local network. 
The last couple of updates also had nothing to do with your fan, but if you still think that the app update caused your issues then you can simply revert to an older version...

**Comment by bittsii** [comment]
@merdok ok, seems very strange to me as well but thank you, will investigate this and hope the Plugin will work again. I really like it and thanks for your work!
