### ISSUE TITLE
dmaker.fan.p15 isn't working.

### ISSUE THREAD

**Issue by yoon1st** [merdok/homebridge-xiaomi-fan#116]
Please help us.

this is the screen shot for my setting & homekit
![image](https://user-images.githubusercontent.com/95070816/172557497-526e6c39-0ba3-4b05-beca-2c3dfd8cd2b8.png)

- If i turn on the Button - It's like it's going to work and then it turns into no response.
![image](https://user-images.githubusercontent.com/95070816/172557760-f920b3e6-3c8b-4b2f-b239-30462683a18e.png)

![image](https://user-images.githubusercontent.com/95070816/172557829-566b8e3d-2100-4213-a353-a2362a3b9c7b.png)

**Comment by merdok** [comment]
What does the homebridge log say?

**Comment by yoon1st** [comment]
First, Xiaomi Fan is doing well [Mi Home App - setting Country : korea, not china]  

and log says

[6/9/2022, 9:32:32 AM] [xiaomifan] [My Xiaomi Fan] Error: Could not connect to device, handshake timeout
[6/9/2022, 9:32:32 AM] [xiaomifan] [My Xiaomi Fan] Error: Could not connect to device, handshake timeout
    at Timeout._onTimeout (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:427:17)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[6/9/2022, 9:32:32 AM] [xiaomifan] [My Xiaomi Fan] Could not connect to the fan! Retrying in 30 seconds!
[6/9/2022, 9:33:04 AM] [xiaomifan] [My Xiaomi Fan] Error: Could not connect to device, handshake timeout
[6/9/2022, 9:33:04 AM] [xiaomifan] [My Xiaomi Fan] Error: Could not connect to device, handshake timeout
    at Timeout._onTimeout (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:427:17)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[6/9/2022, 9:33:04 AM] [xiaomifan] [My Xiaomi Fan] Could not connect to the fan! Retrying in 30 seconds!
[6/9/2022, 9:33:36 AM] [xiaomifan] [My Xiaomi Fan] Error: Could not connect to device, handshake timeout
[6/9/2022, 9:33:36 AM] [xiaomifan] [My Xiaomi Fan] Error: Could not connect to device, handshake timeout
    at Timeout._onTimeout (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:427:17)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[6/9/2022, 9:33:36 AM] [xiaomifan] [My Xiaomi Fan] Could not connect to the fan! Retrying in 30 seconds!

**Comment by merdok** [comment]
Handshake timeout usually means that your token is not correct! Please double check that the token is correct.

**Comment by yoon1st** [comment]
You are a Genius!!!!
My problem is Wrong information!! 

Strangely, both servers had fan information written on them, and there was wrong data without activation on the Chinese server. It was my fault for using it.

After changing to the fan information of the Singapore server (same as the Korean server), it was finally confirmed that it was working well.

Have a nice weekend :)
