### ISSUE TITLE
Error: Network communication is unavailable, device might be destroyed

### ISSUE THREAD

**Issue by LPFchan** [merdok/homebridge-xiaomi-fan#125]
I'm running Homebridge 1.5.0 and homebridge-xiaomi-fan v1.5.9. The fan will give me No Response error on the Home app but it works fine after I restart Homebridge so it's not a bad token, then it happens again once in a blue moon ... rinse and repeat.

```
[20/09/2022, 00:58:41] [xiaomifan] [My Xiaomi Fan] Error: Network communication is unavailable, device might be destroyed
[20/09/2022, 00:58:41] [xiaomifan] [My Xiaomi Fan] Error: Network communication is unavailable, device might be destroyed
    at Network.get socket [as socket] (/var/lib/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:229:10)
    at /var/lib/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:396:16
    at new Promise (<anonymous>)
    at DeviceInfo.handshake (/var/lib/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:392:34)
    at send (/var/lib/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:496:10)
    at /var/lib/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:555:4
    at new Promise (<anonymous>)
    at DeviceInfo.call (/var/lib/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:449:10)
    at Object.call (/var/lib/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/device.js:71:26)
    at Object.loadProperties (/var/lib/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/device.js:222:15)
[20/09/2022, 00:58:41] [xiaomifan] [My Xiaomi Fan] Could not connect to the fan! Retrying in 30 seconds!
[20/09/2022, 00:58:44] [Homebridge UI] Homebridge must be running in insecure mode to control accessories
[20/09/2022, 00:59:11] [xiaomifan] [My Xiaomi Fan] Error: Network communication is unavailable, device might be destroyed
[20/09/2022, 00:59:11] [xiaomifan] [My Xiaomi Fan] Error: Network communication is unavailable, device might be destroyed
    at Network.get socket [as socket] (/var/lib/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:229:10)
    at /var/lib/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:396:16
    at new Promise (<anonymous>)
    at DeviceInfo.handshake (/var/lib/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:392:34)
    at send (/var/lib/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:496:10)
    at /var/lib/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:555:4
    at new Promise (<anonymous>)
    at DeviceInfo.call (/var/lib/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:449:10)
    at Object.call (/var/lib/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/device.js:71:26)
    at Object.loadProperties (/var/lib/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/device.js:222:15)
[20/09/2022, 00:59:11] [xiaomifan] [My Xiaomi Fan] Could not connect to the fan! Retrying in 30 seconds!
[20/09/2022, 00:59:41] [xiaomifan] [My Xiaomi Fan] Error: Network communication is unavailable, device might be destroyed
[20/09/2022, 00:59:41] [xiaomifan] [My Xiaomi Fan] Error: Network communication is unavailable, device might be destroyed
    at Network.get socket [as socket] (/var/lib/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:229:10)
    at /var/lib/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:396:16
    at new Promise (<anonymous>)
    at DeviceInfo.handshake (/var/lib/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:392:34)
    at send (/var/lib/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:496:10)
    at /var/lib/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:555:4
    at new Promise (<anonymous>)
    at DeviceInfo.call (/var/lib/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:449:10)
    at Object.call (/var/lib/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/device.js:71:26)
    at Object.loadProperties (/var/lib/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/device.js:222:15)
[20/09/2022, 00:59:41] [xiaomifan] [My Xiaomi Fan] Could not connect to the fan! Retrying in 30 seconds!
[20/09/2022, 01:00:11] [xiaomifan] [My Xiaomi Fan] Error: Network communication is unavailable, device might be destroyed
[20/09/2022, 01:00:11] [xiaomifan] [My Xiaomi Fan] Error: Network communication is unavailable, device might be destroyed
    at Network.get socket [as socket] (/var/lib/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:229:10)
    at /var/lib/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:396:16
    at new Promise (<anonymous>)
    at DeviceInfo.handshake (/var/lib/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:392:34)
    at send (/var/lib/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:496:10)
    at /var/lib/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:555:4
    at new Promise (<anonymous>)
    at DeviceInfo.call (/var/lib/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:449:10)
    at Object.call (/var/lib/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/device.js:71:26)
    at Object.loadProperties (/var/lib/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/device.js:222:15)
[20/09/2022, 01:00:11] [xiaomifan] [My Xiaomi Fan] Could not connect to the fan! Retrying in 30 seconds!
```

**Comment by merdok** [comment]
This is more or less an issue with the outdated underlaying miio library which is not maintained anymore. What fan do you have?

**Comment by LPFchan** [comment]
MODEL: zhimi.fan.za4

**Comment by merdok** [comment]
You can try to run the homebridge-miot plugin, but it will have limited device support of your fan since it is not a native miot device.

**Comment by guzzzi** [comment]
MIOT is a new Plugin from you?

**Comment by merdok** [comment]
yes, and i consider it as a replacement of this one
