### ISSUE TITLE
No Access to MI smart Standing Fan C1 and cutting the connection to the fan

### ISSUE THREAD

**Issue by panthertom** [merdok/homebridge-xiaomi-fan#26]
Dear merdok,
thanks for your support.

This is my issue, using the plugin with the brand new 1C fan.

Thanks for a response
Kind Regards 
Thomas

I've installed the plugin and did a step by step installation using IP and token. The token was defined and set to the plugin.
But there is no access (no reaction to the settings at my homeKit).
My fan is a MI smart Standing Fan 1C (brand new).

This is what happened during the restart of the home bridge:

[7/20/2020, 3:12:30 PM] [My Xiaomi Fan] Connected to Fan dmaker.fan.1c
(node:367) UnhandledPromiseRejectionWarning: Error: busy.
at Object.reject (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:475:13)
at DeviceInfo.onMessage (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:374:8)
at Socket.<anonymous> (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:160:11)
at Socket.emit (events.js:315:20)
at UDP.onMessage (dgram.js:910:8)
(node:367) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 248)

BTW: 
If i have used the plugin and the token there is no access via the Xiaomi App anymore.
Firmware is the actual version (2.0.4.0003.)
Thanks for your support.

**Comment by merdok** [comment]
There is already a discussion about that here #13  . The plugin can connect to the fan but unfortunately xiaomi changed the commands and possibly even the protocol itself so first someone needs to extract all the commands from the fan. When this is done then adding support for this fan should be pretty straight forward.

**Comment by panthertom** [comment]
Hi merdok,
thanks for your response.

Even if I’m a newbie:
Can I support you anyway?
I’ve read that a kind soul (terriblefox) is already doing this.

Kind regards and thanks again for your support.
Thomas

**Comment by merdok** [comment]
Can you join discord or DM on twitter? I might have some thing but i first require testing, would you be willing to do some live testing with me?

**Comment by panthertom** [comment]
Hi merdok,

i would be a pleasure to do some testing for you
I’m a professional test manager for IT projects.

Perhaps we can do this via zoom or WebEx?

Thanks and kind regards.

Thomas

**Comment by merdok** [comment]
Could you join discord here https://discord.gg/DvWjdU , there is a xiaomi-fan channel.

**Comment by merdok** [comment]
Initial support for the dmaker.fan.1c is now added in version 1.2.0. Could you check it out?

**Comment by panthertom** [comment]
Hi merdok,

ich habe das neue PlugIn installiert.
Die PlugIn Version ist 1.2.

Leider erreiche ich den 1C aktuell nicht.
Kein Button zeigt Wirkung.

Der token ist unverändert, ich werde diesen später / morgen überprüfen.

Dann melde ich mich nochmals.

Danke für due Unterstützung.
Viele Grüße Thomas

**Comment by merdok** [comment]
Du kannst debug log hier posten.

**Comment by panthertom** [comment]
[7/26/2020, 2:45:14 PM] [My Xiaomi Fan] Found Fan dmaker.fan.1c
Der 1C wurde gefunden, jedoch aas immer es auch war:

Alle buttons funktionieren.
Nur der Button für die Bewegung funktioniert nicht
links/rechts wird zu recht ausgesteuert.
[7/26/2020, 2:48:33 PM] [My Xiaomi Fan] The requested command not supported is not supported by this device!
[7/26/2020, 2:48:39 PM] [My Xiaomi Fan] The requested command not supported is not supported by this device!

Danke und viele Grüße

Thomas

**Comment by panthertom** [comment]
Nachtrag für den start:
[7/26/2020, 2:53:37 PM] [My Xiaomi Fan] Found Fan dmaker.fan.1c
[7/26/2020, 2:53:37 PM] [My Xiaomi Fan] Creating MiotFan device!
[7/26/2020, 2:53:37 PM] [My Xiaomi Fan] Setting up fan!
[7/26/2020, 2:53:37 PM] [My Xiaomi Fan] Getting device info.
[7/26/2020, 2:53:37 PM] [My Xiaomi Fan] Got fan did: 241185289.
[7/26/2020, 2:53:37 PM] [My Xiaomi Fan] Doing model specific setup.
[7/26/2020, 2:53:37 PM] [My Xiaomi Fan] Starting property polling.
[7/26/2020, 2:53:37 PM] [My Xiaomi Fan] Setup finished!
[7/26/2020, 2:53:37 PM] [My Xiaomi Fan] Fan model info file already exists, not saving!

Änderung Fan Speed:
[7/26/2020, 2:54:40 PM] [My Xiaomi Fan] Successfully set property power to value false! Result: [{"did":"241185289","siid":2,"piid":1,"code":0}]
[7/26/2020, 2:54:52 PM] [My Xiaomi Fan] Error while polling all properties! Error: Error: busy.
[7/26/2020, 2:54:53 PM] [My Xiaomi Fan] Error while setting property fanspeed to value 2! Error: Error: busy.
[7/26/2020, 2:54:53 PM] [My Xiaomi Fan] Error while setting property power to value true! Error: Error: busy.
[7/26/2020, 2:54:54 PM] [My Xiaomi Fan] Error while setting property fanspeed to value 3! Error: Error: busy.
[7/26/2020, 2:54:54 PM] [My Xiaomi Fan] Error while setting property power to value true! Error: Error: busy.
[7/26/2020, 2:54:55 PM] [My Xiaomi Fan] Error while setting property fanspeed to value 3! Error: Error: busy.
[7/26/2020, 2:54:55 PM] [My Xiaomi Fan] Error while setting property power to value true! Error: Error: busy.
[7/26/2020, 2:54:58 PM] [My Xiaomi Fan] Error while setting property power to value true! Error: Error: busy.

[7/26/2020, 2:54:59 PM] [My Xiaomi Fan] Error while setting property fanspeed to value 2! Error: Error: busy.
[7/26/2020, 2:55:00 PM] [My Xiaomi Fan] Error while setting property fanspeed to value 1! Error: Error: busy.
[7/26/2020, 2:55:01 PM] [My Xiaomi Fan] Error while setting property power to value true! Error: Error: Call to device timed out
[7/26/2020, 2:55:01 PM] [My Xiaomi Fan] Error while setting property fanspeed to value 2! Error: Error: busy.
[7/26/2020, 2:55:02 PM] [My Xiaomi Fan] Error while setting property power to value true! Error: Error: busy.
[7/26/2020, 2:55:03 PM] [My Xiaomi Fan] Successfully set property fanspeed to value 2! Result: [{"did":"241185289","siid":2,"piid":2,"code":0}]
[7/26/2020, 2:55:03 PM] [My Xiaomi Fan] Successfully set property power to value true! Result: [{"did":"241185289","siid":2,"piid":1,"code":0}]
[7/26/2020, 2:55:03 PM] [My Xiaomi Fan] Successfully set property fanspeed to value 3! Result: [{"did":"241185289","siid":2,"piid":2,"code":0}]
[7/26/2020, 2:55:04 PM] [My Xiaomi Fan] Successfully set property power to value true! Result: [{"did":"241185289","siid":2,"piid":1,"code":0}]
[7/26/2020, 2:55:04 PM] [My Xiaomi Fan] Successfully set property fanspeed to value 3! Result: [{"did":"241185289","siid":2,"piid":2,"code":0}]
[7/26/2020, 2:55:04 PM] [My Xiaomi Fan] Successfully set property power to value true! Result: [{"did":"241185289","siid":2,"piid":1,"code":0}]
[7/26/2020, 2:55:08 PM] [My Xiaomi Fan] Successfully set property fanspeed to value 2! Result: [{"did":"241185289","siid":2,"piid":2,"code":0}]
[7/26/2020, 2:55:08 PM] [My Xiaomi Fan] Successfully set property power to value true! Result: [{"did":"241185289","siid":2,"piid":1,"code":0}]
[7/26/2020, 2:55:08 PM] [My Xiaomi Fan] Successfully set property fanspeed to value 1! Result: [{"did":"241185289","siid":2,"piid":2,"code":0}]
[7/26/2020, 2:55:08 PM] [My Xiaomi Fan] Successfully set property power to value true! Result: [{"did":"241185289","siid":2,"piid“:1

button left/right
[7/26/2020, 2:56:32 PM] [My Xiaomi Fan] The requested command not supported is not supported by this device!
[7/26/2020, 2:56:33 PM] [My Xiaomi Fan] The requested command not supported is not supported by this device!

Beim button hier unten habe ich keine Reaktion und keinen Eintrag in das log:

Viele Grüße Thomas

**Comment by merdok** [comment]
Ich sehe das viele der Kommandos durchgegangen sind. Sollte eigentlich gehen. Wir können uns das ja mal auf discord detaillierter angucken.

**Comment by panthertom** [comment]
Gerne - bin jetzt nur belegt durch Verwandtenbesuch. Melde mich dann heute Abend 

Viele Grüße 

Thomas Kerschbaum 

Gesendet von meinem iPhone 11
Dr. Thomas Kerschbaum
thomas.kerschbaum@icloud.com

**Comment by merdok** [comment]
Alles klar 👍

**Comment by panthertom** [comment]
Guten Abend,

bist Du online und hast Zeit für eine Session?

Viele Grüße Thomas

**Comment by merdok** [comment]
Klar, geh mal bitte auf discord. Dann gucken wir mal wo es bei dir hackt.
