### ISSUE TITLE
dmaker.fan.p5 throwing Unhandled promise rejection

### ISSUE THREAD

**Issue by sw2719** [merdok/homebridge-xiaomi-fan#30]
After update to 1.2.0, dmaker.fan.p5 has stopped working. Also 1.2.1 did not fix the issue, but slightly changed things.
Also, downgrading to 1.0.2 which was definitely working didn't help. Also throws UnhandledPromiseRejectionWarning.
It could be my network issue, so i'm investigating.

```
2020. 7. 27. AM 7:59:54 Loaded plugin "homebridge-xiaomi-fan".
2020. 7. 27. AM 7:59:54 Registering accessory "homebridge-xiaomi-fan.xiaomifan"
2020. 7. 27. AM 7:59:55 [Mi Fan 1X] Found Fan dmaker.fan.p5
2020. 7. 27. AM 7:59:55 [Mi Fan 1X] Creating DmakerFan device!
2020. 7. 27. AM 7:59:55 [Mi Fan 1X] Setting up fan!
2020. 7. 27. AM 7:59:55 [Mi Fan 1X] Getting device info.
2020. 7. 27. AM 7:59:55 [Mi Fan 1X] Got fan did: 242265925.
2020. 7. 27. AM 7:59:55 [Mi Fan 1X] Doing model specific setup.
2020. 7. 27. AM 7:59:55 [Mi Fan 1X] Starting property polling.
2020. 7. 27. AM 7:59:55 [Mi Fan 1X] Setup finished!
2020. 7. 27. AM 7:59:55 [Mi Fan 1X] Fan model info file already exists, not saving!
2020. 7. 27. AM 8:00:07 (node:29035) UnhandledPromiseRejectionWarning: Error: Call to device timed out
2020. 7. 27. AM 8:00:07 at Timeout.retry [as _onTimeout] (/root/.hoobs/node_modules/miio/lib/network.js:487:18)
2020. 7. 27. AM 8:00:07 at listOnTimeout (internal/timers.js:549:17)
2020. 7. 27. AM 8:00:07 at processTimers (internal/timers.js:492:7)
2020. 7. 27. AM 8:00:07 (node:29035) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
2020. 7. 27. AM 8:00:07 (node:29035) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2020. 7. 27. AM 8:00:12 [Mi Fan 1X] Poll failed! No response from Fan! Stopping polling! Error: Error: Call to device timed out
2020. 7. 27. AM 8:00:12 [Mi Fan 1X] Trying to reconnect
2020. 7. 27. AM 8:00:12 [Mi Fan 1X] Could not connect to the fan! Retrying in 30 seconds!
2020. 7. 27. AM 8:00:42 [Mi Fan 1X] Connected to Fan dmaker.fan.p5
2020. 7. 27. AM 8:00:42 [Mi Fan 1X] Setting up fan!
2020. 7. 27. AM 8:00:42 [Mi Fan 1X] Getting device info.
2020. 7. 27. AM 8:00:42 [Mi Fan 1X] Doing model specific setup.
2020. 7. 27. AM 8:00:42 [Mi Fan 1X] Starting property polling.
2020. 7. 27. AM 8:00:42 [Mi Fan 1X] Setup finished!
2020. 7. 27. AM 8:00:54 (node:29035) UnhandledPromiseRejectionWarning: Error: Call to device timed out
2020. 7. 27. AM 8:00:54 at Timeout.retry [as _onTimeout] (/root/.hoobs/node_modules/miio/lib/network.js:487:18)
2020. 7. 27. AM 8:00:54 at listOnTimeout (internal/timers.js:549:17)
2020. 7. 27. AM 8:00:54 at processTimers (internal/timers.js:492:7)
2020. 7. 27. AM 8:00:54 (node:29035) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
2020. 7. 27. AM 8:00:55 [Mi Fan 1X] Poll failed! No response from Fan! Stopping polling! Error: Error: busy.
2020. 7. 27. AM 8:00:55 [Mi Fan 1X] Trying to reconnect
2020. 7. 27. AM 8:00:55 [Mi Fan 1X] Could not connect to the fan! Retrying in 30 seconds!
```

**Comment by sw2719** [comment]
Well, resetting the fan fixed it. I don't know why this was happening. But problem solved.

**Comment by merdok** [comment]
Some fans gets "stuck" after wrong commands are sent to them, so it is always a good to unplug it before testing a new update.
