### ISSUE TITLE
Plugin complaining about homebridge version even though it's updated

### ISSUE THREAD

**Issue by 13lievre** [merdok/homebridge-xiaomi-fan#34]
Hi,

Tried to install the plugin today, but it won't work properly. At first it complained about my homebridge version, but then I updated it, but it still says I'm running an older version? What can I do? I've tried rebooting everything, re-installing the plugin, re-adding it to the home app, but nothing is working?

`ERROR LOADING PLUGIN homebridge-xiaomi-fan:
[2020-7-29 22:18:16] Error: Plugin /usr/lib/node_modules/homebridge-xiaomi-fan requires a HomeBridge version of >=1.0.0 which does not satisfy the current HomeBridge version of 0.4.50. You may need to upgrade your installation of HomeBridge.
    at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:56:11)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:153:14)
    at Array.forEach (<anonymous>)
    at Server._loadPlugins (/usr/local/lib/node_modules/homebridge/lib/server.js:145:22)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:57:24)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:32:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)`

`
Error: The requested platform 'xiaomifan' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:134:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
`

Running version 1.1.1 of homebridge. Please let me know if you need anything else to assist me further.

Best,
Simon

**Comment by merdok** [comment]
Well the log states that you are running version 0.4.50 of homebridge. Version 1.0.0 is required. There is something wrong with your homebridge installation. Maybe try to reinstall it?

**Comment by sw2719** [comment]
Homebridge version is fetched from package.json. Check the package.json in homebridge directory. You should see this:
```

{
  "name": "homebridge",
  "description": "HomeKit support for the impatient",
  "version": "1.1.1",
...
```

**Comment by merdok** [comment]
Maybe somehow 2 version of homebridge versions are installed, I think something is messed up with the homebridge installation.

**Comment by entavio** [comment]
You use homebridge in iobroker?! 
Then its the same like here 

https://github.com/merdok/homebridge-xiaomi-fan/issues/17

**Comment by 13lievre** [comment]
Hi, I decided to re-flash the rpi completely, and now everything works fine. Thanks!
