### ISSUE TITLE
Two 2S fans throwing errors 

### ISSUE THREAD

**Issue by CooperCGN** [merdok/homebridge-xiaomi-fan#40]
As the other issue got closed I am opening this here again. Attached is the log with the debug option activated.
[log.txt](https://github.com/merdok/homebridge-xiaomi-fan/files/5019080/log.txt)

**Comment by merdok** [comment]
This is still no debug log which helps me. You enabled miio debug log, but I still have no idea what you exactly do with the fan... Again you need to start homebridge as follows:

`homebridge -D -I`

**Comment by thorstenman** [comment]
Fans running smooth, can be controlled fine. But error messages are back. Constantly getting this every 30 min though fans are activated and running 24/7:

Aug 11 08:19:57 HomeBridge homebridge[470]: [2020-8-11 8:19:57] [xiaomifan] [Fan2] Connected to Fan zhimi.fan.za4
Aug 11 08:19:57 HomeBridge homebridge[470]: (node:470) UnhandledPromiseRejectionWarning: Error: busy.
Aug 11 08:19:57 HomeBridge homebridge[470]:     at Object.reject (/usr/local/lib/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:475:13)
Aug 11 08:19:57 HomeBridge homebridge[470]:     at DeviceInfo.onMessage (/usr/local/lib/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:374:8)
Aug 11 08:19:57 HomeBridge homebridge[470]:     at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:160:11)
Aug 11 08:19:57 HomeBridge homebridge[470]:     at Socket.emit (events.js:315:20)
Aug 11 08:19:57 HomeBridge homebridge[470]:     at UDP.onMessage (dgram.js:910:8)
Aug 11 08:19:57 HomeBridge homebridge[470]: (node:470) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1586)

**Comment by merdok** [comment]
You need to provide me a debug log so that I know from where or what command caused the error.

**Comment by merdok** [comment]
Closing due to inactivity.
