### ISSUE TITLE
 Switches in HomeKit turn on and off every few seconds randomly

### ISSUE THREAD

**Issue by OliHoenig** [merdok/homebridge-xiaomi-fan#52]
Hi merdok,

since Version 1.4.0 the switches in HomeKit-App toggling randomly every couple seconds. 
I can switch the fan on, but it can only be switched off if the button in HomeKit shows "on" during the random switchovers.
See attached GIF. It shows a timespan of 38 seconds with no switching process of a device in HK or HB.

Cheers, Oli

![Malfunction](https://user-images.githubusercontent.com/70107603/94873589-e53f7200-044f-11eb-9b95-c0c691a6ec71.gif)

Debug:
[10/2/2020, 01:43:04] [xiaomifan] [Xiaomi Fan 1C] Connected to Fan dmaker.fan.1c
[10/2/2020, 01:43:04] [xiaomifan] [Xiaomi Fan 1C] Setting up fan!
[10/2/2020, 01:43:04] [xiaomifan] [Xiaomi Fan 1C] Getting device info.
[10/2/2020, 01:43:04] [xiaomifan] [Xiaomi Fan 1C] Got fan did: 241197983.
[10/2/2020, 01:43:04] [xiaomifan] [Xiaomi Fan 1C] Doing model specific setup.
[10/2/2020, 01:43:04] [xiaomifan] [Xiaomi Fan 1C] Adding properties to fan.
[10/2/2020, 01:43:04] [xiaomifan] [Xiaomi Fan 1C] Doing initial properties fetch.
[10/2/2020, 01:43:04] [xiaomifan] [Xiaomi Fan 1C] Setup finished! Fan can now be controlled!
[10/2/2020, 01:43:04] [xiaomifan] [Xiaomi Fan 1C] Successfully saved fan info!

Protocol:
[10/2/2020, 01:43:09] [xiaomifan] [Xiaomi Fan 1C] Connected to Fan dmaker.fan.1c
[10/2/2020, 01:43:14] [xiaomifan] [Xiaomi Fan 1C] Connected to Fan dmaker.fan.1c
[10/2/2020, 01:43:19] [xiaomifan] [Xiaomi Fan 1C] Connected to Fan dmaker.fan.1c
[10/2/2020, 01:43:24] [xiaomifan] [Xiaomi Fan 1C] Connected to Fan dmaker.fan.1c
[10/2/2020, 01:43:29] [xiaomifan] [Xiaomi Fan 1C] Connected to Fan dmaker.fan.1c
[10/2/2020, 01:43:34] [xiaomifan] [Xiaomi Fan 1C] Connected to Fan dmaker.fan.1c
[10/2/2020, 01:43:39] [xiaomifan] [Xiaomi Fan 1C] Connected to Fan dmaker.fan.1c
[10/2/2020, 01:43:44] [xiaomifan] [Xiaomi Fan 1C] Connected to Fan dmaker.fan.1c
[10/2/2020, 01:43:49] [xiaomifan] [Xiaomi Fan 1C] Connected to Fan dmaker.fan.1c
[10/2/2020, 01:43:54] [xiaomifan] [Xiaomi Fan 1C] Connected to Fan dmaker.fan.1c
[10/2/2020, 01:43:59] [xiaomifan] [Xiaomi Fan 1C] Connected to Fan dmaker.fan.1c
[10/2/2020, 01:44:04] [xiaomifan] [Xiaomi Fan 1C] Connected to Fan dmaker.fan.1c
.....

**Comment by Trippersgarage** [comment]
I second the issue, the buttons are switching randomly. I can control the fan, but the switch is randomly changing states (example showing the fan as "off" when in fact it is running).  Using a dmaker.fan.p9

**Comment by merdok** [comment]
@Trippersgarage @OliHoenig 
can you please provide a longer debug log? It seems to me like that fan is constantly disconnecting and connecting and I would need to find out why it is the case. For that a debug log would be helpful.

**Comment by OliHoenig** [comment]
Hi merdok,

hours before your update, there was a Config UI X update, too. It looks like my Roborock vacuum has the same issue now:

![Bildschirmvideo-aufnehmen-2020-10-02-um-10 29 15](https://user-images.githubusercontent.com/70107603/94904129-1ee99a80-049b-11eb-88c4-8d5189224a07.gif)


Here is the debug :-)

{"temp":11.7,"pressure":1014,"humidity":71,"time":1601324388}]}
[10/2/2020, 10:23:44] [WeatherPlus] History Loaded from Persistant Storage
[10/2/2020, 10:23:44] [Roborock S5 Max] STA getDevice | Connected to: 192.168.178.49
[10/2/2020, 10:23:44] [Roborock S5 Max] STA getDevice | Model: roborock.vacuum.s5e
[10/2/2020, 10:23:44] [Roborock S5 Max] STA getDevice | State: charging
[10/2/2020, 10:23:44] [Roborock S5 Max] STA getDevice | FanSpeed: 106
[10/2/2020, 10:23:44] [Roborock S5 Max] STA getDevice | BatteryLevel: 100
[10/2/2020, 10:23:44] [Roborock S5 Max] DEB ensureDevice | roborock.vacuum.s5e | The socket is still on. Reusing it.
[10/2/2020, 10:23:44] [Roborock S5 Max] INF getRoomMap | roborock.vacuum.s5e | Map is 16,952001014178,17,952001015443,18,952001014345,19,952001015446,20,952001015444,22,952001015445
[10/2/2020, 10:23:44] [Roborock S5 Max] INF createRoom | roborock.vacuum.s5e | Room 952001014178 (16)
[10/2/2020, 10:23:44] [Roborock S5 Max] INF createRoom | roborock.vacuum.s5e | Room 952001015443 (17)
[10/2/2020, 10:23:44] [Roborock S5 Max] INF createRoom | roborock.vacuum.s5e | Room 952001014345 (18)
[10/2/2020, 10:23:44] [Roborock S5 Max] INF createRoom | roborock.vacuum.s5e | Room 952001015446 (19)
[10/2/2020, 10:23:44] [Roborock S5 Max] INF createRoom | roborock.vacuum.s5e | Room 952001015444 (20)
[10/2/2020, 10:23:44] [Roborock S5 Max] INF createRoom | roborock.vacuum.s5e | Room 952001015445 (22)
[10/2/2020, 10:23:44] [Roborock S5 Max] DEB ensureDevice | roborock.vacuum.s5e | The socket is still on. Reusing it.
[10/2/2020, 10:23:44] [Roborock S5 Max] INF getSerialNumber | roborock.vacuum.s5e | Serial Number is R0517
[10/2/2020, 10:23:44] [Roborock S5 Max] STA getDevice | Serialnumber: R0517
[10/2/2020, 10:23:44] [Roborock S5 Max] DEB ensureDevice | roborock.vacuum.s5e | The socket is still on. Reusing it.
[10/2/2020, 10:23:44] [Roborock S5 Max] INF getFirmware | roborock.vacuum.s5e | Firmwareversion is 3.5.8_0964
[10/2/2020, 10:23:44] [Roborock S5 Max] STA getDevice | Firmwareversion: 3.5.8_0964
[10/2/2020, 10:23:44] [Roborock S5 Max] DEB ensureDevice | roborock.vacuum.s5e | The socket is still on. Reusing it.
[10/2/2020, 10:23:44] [Roborock S5 Max] DEB getState | roborock.vacuum.s5e | State {"batteryLevel":100,"charging":true,"cleaning":false,"fanSpeed":106} | Props {"state":"charging","batteryLevel":100,"cleanTime":1989,"cleanArea":31.7075,"fanSpeed":106,"in_cleaning":0,"mainBrushWorkTime":24303,"sideBrushWorkTime":24303,"filterWorkTime":24303,"sensorDirtyTime":24169,"waterBoxMode":204}
[10/2/2020, 10:23:44] [Roborock S5 Max] MON changedCleaning | roborock.vacuum.s5e | CleaningState is now false
[10/2/2020, 10:23:44] [Roborock S5 Max] INF changedCleaning | roborock.vacuum.s5e | Cleaning is OFF.
[10/2/2020, 10:23:44] [Roborock S5 Max] MON changedCharging | roborock.vacuum.s5e | ChargingState is now true
[10/2/2020, 10:23:44] [Roborock S5 Max] INF changedCharging | roborock.vacuum.s5e | Charging is active
[10/2/2020, 10:23:44] [Roborock S5 Max] INF changedCharging | roborock.vacuum.s5e | Robot was docked.
[10/2/2020, 10:23:44] [Roborock S5 Max] MON changedSpeed | roborock.vacuum.s5e | FanSpeed is now 106%
[10/2/2020, 10:23:44] [Roborock S5 Max] INF changedSpeed | roborock.vacuum.s5e | Speed was changed to 106% (Custom), for HomeKit 100%
[10/2/2020, 10:23:44] [Roborock S5 Max] DEB changedBattery | roborock.vacuum.s5e | BatteryLevel 100%
[10/2/2020, 10:23:44] [Roborock S5 Max] MON changedPause | roborock.vacuum.s5e | CleaningState is now false
[10/2/2020, 10:23:44] [Roborock S5 Max] INF changedPause | roborock.vacuum.s5e | Paused not possible, no cleaning
[10/2/2020, 10:23:44] [WeatherPlus] **Fakegato-timer: addData  Now { time: 1601627024.669, temp: 13.5, pressure: 996, humidity: 82 }  immediate:  false
[10/2/2020, 10:23:44] [WeatherPlus] **Start Global Fakegato-Timer - 10min**
[10/2/2020, 10:23:46 am] [SmartThings-v2] INFO: INFO: Your plugin version is up-to-date 
[10/2/2020, 10:23:46 am] [SmartThings-v2] NOTICE: Sending Plugin Status to SmartThings | UpdateAvailable: false | newVersion: 2.3.8 
[10/2/2020, 10:23:46 am] [SmartThings-v2] DEBUG: sendUpdateStatus Resp: {"status":"OK"} 
[10/2/2020, 10:23:52] [Roborock S5 Max] DEB getServices | roborock.vacuum.s5e
[10/2/2020, 10:23:52 am] [SmartThings-v2] DEBUG: Configure Cached Accessory: Security Alarm, UUID: 264bc204-2ab5-4664-8d7b-58a2fbbe9540 
[10/2/2020, 10:23:52 am] [SmartThings-v2] DEBUG: Initializing Cached Device alarmSystemStatus_4a28b342-8c9f-4983-9627-8eb22292e136 
[10/2/2020, 10:23:52 am] [SmartThings-v2] DEBUG: Security Alarm ' | ' 'alarm_system'
[10/2/2020, 10:23:52 am] [SmartThings-v2] GOOD: [CHARACTERISTIC (function SecuritySystemCurrentState() {
        var _this = _super.call(this, 'Security System Current State', SecuritySystemCurrentState.UUID) || this;
        _this.setProps({
            format: "uint8" /* UINT8 */,
            maxValue: 4,
            minValue: 0,
            validValues: [0, 1, 2, 3, 4],
            perms: ["pr" /* READ */, "ev" /* NOTIFY */]
        });
        _this.value = _this.getDefaultValue();
        return _this;
    }) GET] alarmSystemStatus (Security Alarm) | LastUpdate: (Fri Oct 02 2020 10:23:52 GMT+0200 (Central European Summer Time)) | Value: (3) 
[10/2/2020, 10:23:52 am] [SmartThings-v2] GOOD: [CHARACTERISTIC (function SecuritySystemTargetState() {
        var _this = _super.call(this, 'Security System Target State', SecuritySystemTargetState.UUID) || this;
        _this.setProps({
            format: "uint8" /* UINT8 */,
            maxValue: 3,
            minValue: 0,
            validValues: [0, 1, 2, 3],
            perms: ["pr" /* READ */, "pw" /* WRITE */, "ev" /* NOTIFY */]
        });
        _this.value = _this.getDefaultValue();
        return _this;
    }) GET] alarmSystemStatus (Security Alarm) | LastUpdate: (Fri Oct 02 2020 10:23:52 GMT+0200 (Central European Summer Time)) | Value: (3) 
[10/2/2020, 10:23:52 am] [SmartThings-v2] GOOD: [CHARACTERISTIC (function SecuritySystemTargetState() {
        var _this = _super.call(this, 'Security System Target State', SecuritySystemTargetState.UUID) || this;
        _this.setProps({
            format: "uint8" /* UINT8 */,
            maxValue: 3,
            minValue: 0,
            validValues: [0, 1, 2, 3],
            perms: ["pr" /* READ */, "pw" /* WRITE */, "ev" /* NOTIFY */]
        });
        _this.value = _this.getDefaultValue();
        return _this;
    }) GET] alarmSystemStatus (Security Alarm) | LastUpdate: (Fri Oct 02 2020 10:23:52 GMT+0200 (Central European Summer Time)) | Value: (3) 
[10/2/2020, 10:23:52 am] [SmartThings-v2] DEBUG: Configure Cached Accessory: Trockner, UUID: 3bc055f8-319a-419d-a522-e0357a49b4d5 
[10/2/2020, 10:23:52 am] [SmartThings-v2] DEBUG: Initializing Cached Device 99831b4d-6769-d617-77dd-5decde1f0da6 
[10/2/2020, 10:23:52 am] [SmartThings-v2] DEBUG: Trockner ' | ' 'switch_device'
[10/2/2020, 10:23:52 am] [SmartThings-v2] GOOD: [CHARACTERISTIC (function On() {
        var _this = _super.call(this, 'On', On.UUID) || this;
        _this.setProps({
            format: "bool" /* BOOL */,
            perms: ["pr" /* READ */, "pw" /* WRITE */, "ev" /* NOTIFY */]
        });
        _this.value = _this.getDefaultValue();
        return _this;
    }) GET] switch (Trockner) | LastUpdate: (Fri Oct 02 2020 10:23:52 GMT+0200 (Central European Summer Time)) | Value: (false) 
[10/2/2020, 10:23:52 am] [SmartThings-v2] GOOD: [CHARACTERISTIC (function On() {
        var _this = _super.call(this, 'On', On.UUID) || this;
        _this.setProps({
            format: "bool" /* BOOL */,
            perms: ["pr" /* READ */, "pw" /* WRITE */, "ev" /* NOTIFY */]
        });
        _this.value = _this.getDefaultValue();
        return _this;
    }) GET] switch (Trockner) | LastUpdate: (Fri Oct 02 2020 10:23:52 GMT+0200 (Central European Summer Time)) | Value: (false) 
[10/2/2020, 10:23:52 am] [SmartThings-v2] DEBUG: Configure Cached Accessory: Waschmaschine, UUID: f4ede488-02de-4cf4-9e76-b23946f23d0e 
[10/2/2020, 10:23:52 am] [SmartThings-v2] DEBUG: Initializing Cached Device 9ee6edc3-5355-1a4f-224d-952d1266bc03 
[10/2/2020, 10:23:52 am] [SmartThings-v2] DEBUG: Waschmaschine ' | ' 'switch_device'
[10/2/2020, 10:23:52 am] [SmartThings-v2] GOOD: [CHARACTERISTIC (function On() {
        var _this = _super.call(this, 'On', On.UUID) || this;
        _this.setProps({
            format: "bool" /* BOOL */,
            perms: ["pr" /* READ */, "pw" /* WRITE */, "ev" /* NOTIFY */]
        });
        _this.value = _this.getDefaultValue();
        return _this;
    }) GET] switch (Waschmaschine) | LastUpdate: (Fri Oct 02 2020 10:23:52 GMT+0200 (Central European Summer Time)) | Value: (false) 
[10/2/2020, 10:23:52 am] [SmartThings-v2] GOOD: [CHARACTERISTIC (function On() {
        var _this = _super.call(this, 'On', On.UUID) || this;
        _this.setProps({
            format: "bool" /* BOOL */,
            perms: ["pr" /* READ */, "pw" /* WRITE */, "ev" /* NOTIFY */]
        });
        _this.value = _this.getDefaultValue();
        return _this;
    }) GET] switch (Waschmaschine) | LastUpdate: (Fri Oct 02 2020 10:23:52 GMT+0200 (Central European Summer Time)) | Value: (false) 
[10/2/2020, 10:23:52] [xiaomifan] Found cached accessory Xiaomi Fan 1C
[10/2/2020, 10:23:52] [xiaomifan] Removing all cached accessories
[10/2/2020, 10:23:52] [xiaomifan] Init - initializing devices
[10/2/2020, 10:23:52] [xiaomifan] [Xiaomi Fan 1C] Init - got fan configuration, initializing device with name: Xiaomi Fan 1C
[10/2/2020, 10:23:52] [xiaomifan] [Xiaomi Fan 1C] Cached fan model dmaker.fan.1c found! Creating fan device!
[10/2/2020, 10:23:52] [xiaomifan] [Xiaomi Fan 1C] Creating MiotDmakerAcFan device!
[10/2/2020, 10:23:52 am] [SmartThings-v2] INFO: Fetching SmartThings-v2 Devices. NOTICE: This may take a moment if you have a large number of device data is being loaded! 
[10/2/2020, 10:23:52 am] [SmartThings-v2] GOOD: Refreshing All Device Data | Source: (First Launch) 
Setup Payload:
X-HM://0023U2UDROILO
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:

                                                      
Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ │     
    └────────────┘     
                       
[10/2/2020, 10:23:52] Error: listen EADDRINUSE: address already in use :::51019
    at Server.setupListenHandle [as _listen2] (net.js:1313:16)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1447:7)
    at EventedHTTPServer._this.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:84:21)
    at HAPServer._this.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:236:22)
    at Bridge.Accessory._this.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:999:18)
    at Server.publishBridge (/usr/local/lib/node_modules/homebridge/src/server.ts:190:17)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:162:24
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:161:5)
[10/2/2020, 10:23:52 am] [SmartThings-v2] ERROR: uncaughtException: listen EADDRINUSE: address already in use :::51019
Error: listen EADDRINUSE: address already in use :::51019
    at Server.setupListenHandle [as _listen2] (net.js:1313:16)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1447:7)
    at EventedHTTPServer._this.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:84:21)
    at HAPServer._this.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:236:22)
    at Bridge.Accessory._this.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:999:18)
    at Server.publishBridge (/usr/local/lib/node_modules/homebridge/src/server.ts:190:17)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:162:24
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:161:5) 
[10/2/2020, 10:23:52] Got SIGTERM, shutting down Homebridge...
(node:20493) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: Cannot stop advertisement when service wasn't yet advertised!
    at Advertiser.stopAdvertising (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Advertiser.ts:97:11)
    at Advertiser.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Advertiser.ts:102:16)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Advertiser.js:46:23)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Advertiser.js:27:53)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Advertiser.js:21:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Advertiser.js:17:12)
    at Advertiser.shutdown (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Advertiser.js:126:16)
    at Bridge.Accessory._this.unpublish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1025:24)
    at Server.teardown (/usr/local/lib/node_modules/homebridge/src/server.ts:615:17)
(node:20493) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:20493) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[10/2/2020, 10:23:52] [xiaomifan] [Xiaomi Fan 1C] Connected to Fan dmaker.fan.1c
[10/2/2020, 10:23:52] [xiaomifan] [Xiaomi Fan 1C] Setting up fan!
[10/2/2020, 10:23:52] [xiaomifan] [Xiaomi Fan 1C] Getting device info.
[10/2/2020, 10:23:52] [xiaomifan] [Xiaomi Fan 1C] Got fan did: 241197983.
[10/2/2020, 10:23:52] [xiaomifan] [Xiaomi Fan 1C] Doing model specific setup.
[10/2/2020, 10:23:52] [xiaomifan] [Xiaomi Fan 1C] Adding properties to fan.
[10/2/2020, 10:23:52] [xiaomifan] [Xiaomi Fan 1C] Doing initial properties fetch.
[10/2/2020, 10:23:52] [xiaomifan] [Xiaomi Fan 1C] Setup finished! Fan can now be controlled!
[10/2/2020, 10:23:52] [xiaomifan] [Xiaomi Fan 1C] Successfully saved fan info!
[10/2/2020, 10:23:53 am] [SmartThings-v2] NOTICE: Temperature Unit is Now: (C) 
[10/2/2020, 10:23:53 am] [SmartThings-v2] NOTICE: Updating Global Values | HubIP: 192.168.178.37 | UseLocal: false 
[10/2/2020, 10:23:53 am] [SmartThings-v2] WARN: Devices to Remove: (0) []
[10/2/2020, 10:23:53 am] [SmartThings-v2] INFO: Devices to Update: (3) 
[10/2/2020, 10:23:53 am] [SmartThings-v2] GOOD: Devices to Create: (0) []
[10/2/2020, 10:23:53 am] [SmartThings-v2] DEBUG: Loading Existing Device (Security Alarm) | (alarmSystemStatus_4a28b342-8c9f-4983-9627-8eb22292e136) 
[10/2/2020, 10:23:53 am] [SmartThings-v2] DEBUG: Security Alarm ' | ' 'alarm_system'
[10/2/2020, 10:23:53 am] [SmartThings-v2] GOOD: [CHARACTERISTIC (function SecuritySystemCurrentState() {
        var _this = _super.call(this, 'Security System Current State', SecuritySystemCurrentState.UUID) || this;
        _this.setProps({
            format: "uint8" /* UINT8 */,
            maxValue: 4,
            minValue: 0,
            validValues: [0, 1, 2, 3, 4],
            perms: ["pr" /* READ */, "ev" /* NOTIFY */]
        });
        _this.value = _this.getDefaultValue();
        return _this;
    }) GET] alarmSystemStatus (Security Alarm) | LastUpdate: (Fri Oct 02 2020 10:23:53 GMT+0200 (Central European Summer Time)) | Value: (3) 
[10/2/2020, 10:23:53 am] [SmartThings-v2] GOOD: [CHARACTERISTIC (function SecuritySystemTargetState() {
        var _this = _super.call(this, 'Security System Target State', SecuritySystemTargetState.UUID) || this;
        _this.setProps({
            format: "uint8" /* UINT8 */,
            maxValue: 3,
            minValue: 0,
            validValues: [0, 1, 2, 3],
            perms: ["pr" /* READ */, "pw" /* WRITE */, "ev" /* NOTIFY */]
        });
        _this.value = _this.getDefaultValue();
        return _this;
    }) GET] alarmSystemStatus (Security Alarm) | LastUpdate: (Fri Oct 02 2020 10:23:53 GMT+0200 (Central European Summer Time)) | Value: (3) 
[10/2/2020, 10:23:53 am] [SmartThings-v2] DEBUG: Loading Existing Device (Trockner) | (99831b4d-6769-d617-77dd-5decde1f0da6) 
[10/2/2020, 10:23:53 am] [SmartThings-v2] DEBUG: Trockner ' | ' 'switch_device'
[10/2/2020, 10:23:53 am] [SmartThings-v2] GOOD: [CHARACTERISTIC (function On() {
        var _this = _super.call(this, 'On', On.UUID) || this;
        _this.setProps({
            format: "bool" /* BOOL */,
            perms: ["pr" /* READ */, "pw" /* WRITE */, "ev" /* NOTIFY */]
        });
        _this.value = _this.getDefaultValue();
        return _this;
    }) GET] switch (Trockner) | LastUpdate: (Fri Oct 02 2020 10:23:53 GMT+0200 (Central European Summer Time)) | Value: (false) 
[10/2/2020, 10:23:53 am] [SmartThings-v2] DEBUG: Loading Existing Device (Waschmaschine) | (9ee6edc3-5355-1a4f-224d-952d1266bc03) 
[10/2/2020, 10:23:53 am] [SmartThings-v2] DEBUG: Waschmaschine ' | ' 'switch_device'
[10/2/2020, 10:23:53 am] [SmartThings-v2] GOOD: [CHARACTERISTIC (function On() {
        var _this = _super.call(this, 'On', On.UUID) || this;
        _this.setProps({
            format: "bool" /* BOOL */,
            perms: ["pr" /* READ */, "pw" /* WRITE */, "ev" /* NOTIFY */]
        });
        _this.value = _this.getDefaultValue();
        return _this;
    }) GET] switch (Waschmaschine) | LastUpdate: (Fri Oct 02 2020 10:23:53 GMT+0200 (Central European Summer Time)) | Value: (false) 
[10/2/2020, 10:23:53 am] [SmartThings-v2] ALERT: Total Initialization Time: (1 seconds) 
[10/2/2020, 10:23:53 am] [SmartThings-v2] NOTICE: Unknown Capabilities: ["Ocf","Execute","Remote Control Status","Dryer Mode","Dryer Operating State","Power Consumption Report","custom.error","custom.disabledCapabilities","custom.dthVersion","custom.dryerDryLevel","custom.dryerWrinklePrevent","custom.supportedOptions","custom.jobBeginningStatus","samsungce.dryerCycle","samsungce.dryerAutoCycleLink","Washer Mode","Washer Operating State","custom.washerAutoDetergent","custom.washerAutoSoftener","custom.washerRinseCycles","custom.washerSoilLevel","custom.washerSpinLevel","custom.washerWaterTemperature","custom.washerAddwashAlarm","samsungce.washerCycle"] 
[10/2/2020, 10:23:53 am] [SmartThings-v2] INFO: SmartThings DeviceCache Size: (3) 
[10/2/2020, 10:23:53 am] [SmartThings-v2] INFO: WebServer Initiated... 
[10/2/2020, 10:23:53 am] [SmartThings-v2] INFO: Sending StartDirect Request to SmartThings | SendToLocalHub: (false) 
[10/2/2020, 10:23:53 am] [SmartThings-v2] INFO: Direct Connect Active | Listening at 192.168.178.45:8001 
[10/2/2020, 10:23:53 am] [SmartThings-v2] DEBUG: sendStartDirect Resp: {"status":"OK"} 
[10/2/2020, 10:23:53 am] [SmartThings-v2] INFO: SmartThings-v2 Hub Communication Established

**Comment by Trippersgarage** [comment]
Hi Merdok.

`[37m[10/2/2020, 4:38:44 PM] [39m[36m[xiaomifan] [39m[90m[Jim] Trying to reconnect[39m
[37m[10/2/2020, 4:38:44 PM] [39m[36m[xiaomifan] [39m[Jim] Connected to Fan dmaker.fan.p9
[37m[10/2/2020, 4:38:44 PM] [39m[36m[xiaomifan] [39m[90m[Jim] Setting up fan![39m
[37m[10/2/2020, 4:38:44 PM] [39m[36m[xiaomifan] [39m[90m[Jim] Getting device info.[39m
[37m[10/2/2020, 4:38:44 PM] [39m[36m[xiaomifan] [39m[90m[Jim] Doing model specific setup.[39m
[37m[10/2/2020, 4:38:44 PM] [39m[36m[xiaomifan] [39m[90m[Jim] Adding properties to fan.[39m
[37m[10/2/2020, 4:38:44 PM] [39m[36m[xiaomifan] [39m[90m[Jim] Doing initial properties fetch.[39m
[37m[10/2/2020, 4:38:44 PM] [39m[36m[xiaomifan] [39m[90m[Jim] Setup finished! Fan can now be controlled![39m
[37m[10/2/2020, 4:38:44 PM] [39m[36m[xiaomifan] [39m[90m[Jim] Successfully saved fan info![39m
[37m[10/2/2020, 4:38:49 PM] [39m[36m[xiaomifan] [39m[90m[Jim] Poll failed! No response from Fan! Stopping polling! Error: TypeError: this.miioFanDevice.requestAllProperties is not a function[39m
[37m[10/2/2020, 4:38:49 PM] [39m[36m[xiaomifan] [39m[90m[Jim] Trying to reconnect[39m
[37m[10/2/2020, 4:38:49 PM] [39m[36m[xiaomifan] [39m[Jim] Connected to Fan dmaker.fan.p9
[37m[10/2/2020, 4:38:49 PM] [39m[36m[xiaomifan] [39m[90m[Jim] Setting up fan![39m
[37m[10/2/2020, 4:38:49 PM] [39m[36m[xiaomifan] [39m[90m[Jim] Getting device info.[39m
[37m[10/2/2020, 4:38:49 PM] [39m[36m[xiaomifan] [39m[90m[Jim] Doing model specific setup.[39m
[37m[10/2/2020, 4:38:49 PM] [39m[36m[xiaomifan] [39m[90m[Jim] Adding properties to fan.[39m
[37m[10/2/2020, 4:38:49 PM] [39m[36m[xiaomifan] [39m[90m[Jim] Doing initial properties fetch.[39m
[37m[10/2/2020, 4:38:49 PM] [39m[36m[xiaomifan] [39m[90m[Jim] Setup finished! Fan can now be controlled![39m
`

Thats what I get in an endless loop. To add, the home bridge UI update made no difference in my case, this issue started with the Xiaomi-fan update and its still having the same issue after the UI update.

**Comment by merdok** [comment]
Thanks guys, I see the issue now😅 Sorry, I do not own a miot fan device like the ones you are using so I cannot test my changes locally for such devices. 

Can somebody of you do a quick test for me?
You would need to edit the file:
lib/devices/miot/MiotFan.js
And change line 43 to:
return this.requestAllProperties()

That should fix the issue for you.

**Comment by Trippersgarage** [comment]
I must be in idiot as I cannot find that file anywhere. I'm on a raspy pi4 running rasp pi OS. What am I missing?

**Comment by merdok** [comment]
You have start in the homebridge-xiaomi-fan directory which is located where all of your npm packages are installed.

I think the default for a global installation is:
/us/local/lib/node_modules/

**Comment by merdok** [comment]
Should be fixed in version 1.4.1

**Comment by OliHoenig** [comment]
Confirmed!!! Issue fixed in 1.4.1

Thank you so much!!!!!

**Comment by Trippersgarage** [comment]
Can confirm the issue is fixed on my end as well Thank you Merdok for the assistance and the plug in in general. Great plug in and brilliant support from you. Cheers!
