### ISSUE TITLE
can connect fan but can't control fan

### ISSUE THREAD

**Issue by biye1999** [merdok/homebridge-xiaomi-fan#6]
@merdok It is a cool plugin, but I meet some troubles. I run homebridge in my MacBook and I got the token from android apk without miio.
Here is log:
```
[5/10/2020, 11:45:38 PM] [My Xiaomi Fan] Xiaomi Fan - connected to Fan
[5/10/2020, 11:45:38 PM] [My Xiaomi Fan] MiioDevice {
  model=dmaker.fan.p5,
  types=miio,
  capabilities=
}
false
false
(node:18623) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'log' of undefined
    at /usr/local/lib/node_modules/homebridge-xiaomi-fan/index.js:312:26
(node:18623) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18623) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:18623) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'log' of undefined
    at /usr/local/lib/node_modules/homebridge-xiaomi-fan/index.js:312:26
(node:18623) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:18623) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'log' of undefined
    at /usr/local/lib/node_modules/homebridge-xiaomi-fan/index.js:312:26
(node:18623) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:18623) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'log' of undefined
    at /usr/local/lib/node_modules/homebridge-xiaomi-fan/index.js:312:26
(node:18623) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
ifconfig: sysctl IFDATA_SUPPLEMENTAL: Cannot allocate memory
```
Thanks a lot.

**Comment by merdok** [comment]
You are right, this was bug. I fixed it! Can you please try to replace the index.js manually and check out if the crash is gone?

**Comment by biye1999** [comment]
Okay, I replace the index.js and it fixed some crash, but it also display false.
when I restart homebridge, the code is ended at:
```shell
[5/11/2020, 7:34:04 AM] [My Xiaomi Fan] Xiaomi Fan - connected to Fan
[5/11/2020, 7:34:04 AM] [My Xiaomi Fan] MiioDevice {
  model=dmaker.fan.p5,
  types=miio,
  capabilities=
}
```
When I click the 'turn on the fan' button, the log say `false`
Here is log:
```shell
[5/11/2020, 7:34:04 AM] [My Xiaomi Fan] Xiaomi Fan - connected to Fan
[5/11/2020, 7:34:04 AM] [My Xiaomi Fan] MiioDevice {
  model=dmaker.fan.p5,
  types=miio,
  capabilities=
}
false
false
false
false
false
```
@merdok

**Comment by merdok** [comment]
Can you start homebridge in debug mode with the -D parameter and check the log?

**Comment by biye1999** [comment]
@merdok 
Yes, here is the log from debug mode. Thanks a lot.
```shell
[5/12/2020, 06:04:23] [My Xiaomi Fan] Xiaomi Fan - connected to Fan
[5/12/2020, 06:04:23] [My Xiaomi Fan] MiioDevice {
  model=dmaker.fan.p5,
  types=miio,
  capabilities=
}
[5/12/2020, 06:04:23] [My Xiaomi Fan] Xiaomi Fan - error occured could not write fan model info [Error: ENOENT: no such file or directory, open '~/.xiaomiFan/info_1921680112_2314c5ed5048c068fdadffd747f3afc3'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '~/.xiaomiFan/info_1921680112_2314c5ed5048c068fdadffd747f3afc3'
}

[5/12/2020, 06:04:41] [My Xiaomi Fan] Xiaomi Fan - Fan found
[5/12/2020, 06:04:43] [Config] Homebridge Config UI X v4.18.0 is listening on :: port 8581
[5/12/2020, 06:04:46] [My Xiaomi Fan] Xiaomi Fan - Fan found
[5/12/2020, 06:04:46] [Config] Added new user: admin
[5/12/2020, 06:04:46] [Config] Username and password have been set to default:
[5/12/2020, 06:04:46] [Config] Username: admin
[5/12/2020, 06:04:46] [Config] Password: admin
[5/12/2020, 06:04:51] [My Xiaomi Fan] Xiaomi Fan - Fan found
[5/12/2020, 06:06:08] [My Xiaomi Fan] Xiaomi Fan - Fan found
[5/12/2020, 06:06:12] [My Xiaomi Fan] Xiaomi Fan - got power state from fan: true
true
[5/12/2020, 06:06:12] [My Xiaomi Fan] Xiaomi Fan - got mode from fan: natural
[5/12/2020, 06:06:13] [My Xiaomi Fan] Xiaomi Fan - got speed level from fan: true. Mode: natural
[5/12/2020, 06:06:13] [My Xiaomi Fan] Xiaomi Fan - got swing mode state from fan: true
[5/12/2020, 06:06:13] [My Xiaomi Fan] Xiaomi Fan - got child lock state from fan: false
[5/12/2020, 06:06:13] [My Xiaomi Fan] Xiaomi Fan - Fan found
[5/12/2020, 06:06:13] [My Xiaomi Fan] Xiaomi Fan - got buzzer state from fan: true
[5/12/2020, 06:06:14] [My Xiaomi Fan] Xiaomi Fan - got led state from fan: true
[5/12/2020, 06:06:15] [My Xiaomi Fan] Xiaomi Fan - got child lock state from fan: false
[5/12/2020, 06:06:15] [My Xiaomi Fan] Xiaomi Fan - got power state from fan: true
true
[5/12/2020, 06:06:15] [My Xiaomi Fan] Xiaomi Fan - got mode from fan: natural
[5/12/2020, 06:06:15] [My Xiaomi Fan] Xiaomi Fan - got speed level from fan: true. Mode: natural
[5/12/2020, 06:06:15] [My Xiaomi Fan] Xiaomi Fan - got swing mode state from fan: true
[5/12/2020, 06:06:15] [My Xiaomi Fan] Xiaomi Fan - got buzzer state from fan: true
[5/12/2020, 06:06:16] [My Xiaomi Fan] Xiaomi Fan - got led state from fan: true
[5/12/2020, 06:06:18] [My Xiaomi Fan] Xiaomi Fan - Fan found

[5/12/2020, 06:06:33] [My Xiaomi Fan] Xiaomi Fan - Fan found
[5/12/2020, 06:06:36] [My Xiaomi Fan] Xiaomi Fan - got swing mode state from fan: true
[5/12/2020, 06:06:36] [My Xiaomi Fan] Xiaomi Fan - got power state from fan: true
true
[5/12/2020, 06:06:36] [My Xiaomi Fan] Xiaomi Fan - got mode from fan: natural
[5/12/2020, 06:06:36] [My Xiaomi Fan] Xiaomi Fan - got speed level from fan: true. Mode: natural
[5/12/2020, 06:06:36] [My Xiaomi Fan] Xiaomi Fan - got child lock state from fan: false
[5/12/2020, 06:06:37] [My Xiaomi Fan] Xiaomi Fan - got buzzer state from fan: true
[5/12/2020, 06:06:37] [My Xiaomi Fan] Xiaomi Fan - got led state from fan: true
[5/12/2020, 06:06:38] [My Xiaomi Fan] Xiaomi Fan - Fan found
(node:3348) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'log' of undefined
    at /usr/local/lib/node_modules/homebridge-xiaomi-fan/index.js:312:26
(node:3348) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3348) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[5/12/2020, 06:06:51] [My Xiaomi Fan] Xiaomi Fan - error while setting power state to: on. Error: Error: Call to device timed out
    at Timeout.retry [as _onTimeout] (/usr/local/lib/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:487:18)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  code: 'timeout'
}
[5/12/2020, 06:06:53] [My Xiaomi Fan] Xiaomi Fan - Fan found
[5/12/2020, 06:06:58] [My Xiaomi Fan] Xiaomi Fan - Fan found
[5/12/2020, 06:07:03] [My Xiaomi Fan] Xiaomi Fan - Fan found
[5/12/2020, 06:07:04] [My Xiaomi Fan] Xiaomi Fan - error while setting buzzer state to: false. Error: Error: Call to device timed out
    at Timeout.retry [as _onTimeout] (/usr/local/lib/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:487:18)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  code: 'timeout'
}
[5/12/2020, 06:07:08] [My Xiaomi Fan] Xiaomi Fan - Fan found
(node:3348) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'log' of undefined
    at /usr/local/lib/node_modules/homebridge-xiaomi-fan/index.js:312:26
    at runNextTicks (internal/process/task_queues.js:62:5)
    at listOnTimeout (internal/timers.js:518:9)
    at processTimers (internal/timers.js:492:7)
(node:3348) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[5/12/2020, 06:07:09] [My Xiaomi Fan] Xiaomi Fan - error while setting power state to: on. Error: Error: Call to device timed out
    at Timeout.retry [as _onTimeout] (/usr/local/lib/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:487:18)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  code: 'timeout'
}
[5/12/2020, 06:07:13] [My Xiaomi Fan] Xiaomi Fan - Fan found
[5/12/2020, 06:07:18] [My Xiaomi Fan] Xiaomi Fan - Fan found
(node:3348) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'log' of undefined
    at /usr/local/lib/node_modules/homebridge-xiaomi-fan/index.js:312:26
(node:3348) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
[5/12/2020, 06:07:22] [My Xiaomi Fan] Xiaomi Fan - error while setting power state to: on. Error: Error: Call to device timed out
    at Timeout.retry [as _onTimeout] (/usr/local/lib/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:487:18)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  code: 'timeout'
}
[5/12/2020, 06:07:23] [My Xiaomi Fan] Xiaomi Fan - Fan found
[5/12/2020, 06:07:28] [My Xiaomi Fan] Xiaomi Fan - Fan found
[5/12/2020, 06:07:33] [My Xiaomi Fan] Xiaomi Fan - Fan found
```

**Comment by merdok** [comment]
You are getting a timeout when sending commands to the fan. I have no idea why this is happening. Is the fan reachable? Are you able to ping it?

**Comment by biye1999** [comment]
Yes, I'm able to ping my fan's ip
<img width="648" alt="image" src="https://user-images.githubusercontent.com/62197631/81815501-a2423800-955c-11ea-99e5-ff7eaad436c1.png">
I try it again and the log said: 
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/62197631/81815807-0d8c0a00-955d-11ea-8118-a44f468f0dc9.png">
@merdok What can I do to fix it? Did you have some suggestions? Thanks for your watching again!
My family haven't any XiaoMi phone, so it's terrible to control the fan through Mi-Home App.

**Comment by merdok** [comment]
Sorry, i have unfortunately no idea why you are getting timeouts even when you are able to ping the fan. Maybe your device token is wrong?

**Comment by kapor00** [comment]
Hi i set it up, it appears in homekit but say ,,updating,, or ,,no response,, this is what i get in homekit terminal. Do you have an idea why is this happening?

Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
    at xiaomiFanAccessory.getPowerState (/usr/local/lib/node_modules/homebridge-xiaomi-fan/index.js:356:9)
    at Active.emit (events.js:315:20)
    at Active.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at Active.Characteristic._this.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:462:12)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1215:22
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._this._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1143:10)
    at HAPServer.emit (events.js:315:20)
    at HAPServer.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)

**Comment by merdok** [comment]
You have no connection to the fan. Maybe your ip or token is wrong? 
Anyway this should not crash, this is an error which i will fix, but it should not happend when the connection to the fan is established.

**Comment by sw2719** [comment]
Having the same problem. 
```
0|hoobs  | [My Xiaomi Fan] Xiaomi Fan - error while setting power state to: off. Error: Error: Call to device timed out
0|hoobs  |     at Timeout.retry [as _onTimeout] (/root/.hoobs/node_modules/miio/lib/network.js:487:18)
0|hoobs  |     at listOnTimeout (internal/timers.js:549:17)
0|hoobs  |     at processTimers (internal/timers.js:492:7) {
0|hoobs  |   code: 'timeout'
0|hoobs  | }
```
My IP and token are correct. Works using homebridge-mi-fan plugin.
I really wanna use yours though. I am using a Mi Standing Fan 1X, or dmaker.fan.p5.

**Comment by merdok** [comment]
This is a strange isst which I would need to debug somehow. Since my fan does not rub into Timeouts I cannot do myself. I guess if someone would be ok with doing a teamviewer session with me to debug the issue then that would be helpful...

**Comment by sw2719** [comment]
I guess it's only happening to dmaker.fan.p5 (1X)? Maybe I could teamviewer you in. I'm running HOOBS in Debian Chroot running on Synology NAS.

```
0|hoobs  | [My Xiaomi Fan] Xiaomi Fan - error while requesting mode: Error: busy.
0|hoobs  |     at Object.reject (/root/.hoobs/node_modules/miio/lib/network.js:475:13)
0|hoobs  |     at DeviceInfo.onMessage (/root/.hoobs/node_modules/miio/lib/network.js:374:8)
0|hoobs  |     at Socket.<anonymous> (/root/.hoobs/node_modules/miio/lib/network.js:160:11)
0|hoobs  |     at Socket.emit (events.js:310:20)
0|hoobs  |     at UDP.onMessage [as onmessage] (dgram.js:924:8) {
0|hoobs  |   code: -30012
0|hoobs  | }
```
Noting another kind of error.

**Comment by sw2719** [comment]
Also, it seems to be fetching wrong state data from the fan.
```
2020. 6. 23. 오후 5:28:23 [My Xiaomi Fan] Xiaomi Fan - got speed level from fan: true. Mode: natural
2020. 6. 23. 오후 5:28:23 [My Xiaomi Fan] Xiaomi Fan - got child lock state from fan: false
2020. 6. 23. 오후 5:28:23 [My Xiaomi Fan] Xiaomi Fan - got swing mode state from fan: true
2020. 6. 23. 오후 5:28:23 true
2020. 6. 23. 오후 5:28:23 [My Xiaomi Fan] Xiaomi Fan - got mode from fan: natural
2020. 6. 23. 오후 5:28:23 [My Xiaomi Fan] Xiaomi Fan - got power state from fan: true
2020. 6. 23. 오후 5:28:23 [My Xiaomi Fan] Xiaomi Fan - got speed level from fan: true. Mode: natural
2020. 6. 23. 오후 5:28:24 true
2020. 6. 23. 오후 5:28:24 [My Xiaomi Fan] Xiaomi Fan - got mode from fan: natural
``` 
My fan does not have natural wind mode on, nor swing mode.

**Comment by merdok** [comment]
Ok, I checked the other plugin and as it seems the dmaker fans have a slightly different api then the standard xiaomi fans. I think I could use that info from the other plugin to make the smaller fan working, but I think an additional teamviewer session to check the commands and what response the fan is giving would help me really much. Could you contact me over Twitter so we could set something up?

**Comment by sw2719** [comment]
@merdok I'm outside right now, so I will DM you as soon as I get back home.

**Comment by sw2719** [comment]
@merdok Your DM is blocked from non-following. Could you check your twitter please? Or discord would work too if you use it.

**Comment by merdok** [comment]
Wrote you on Twitter!

**Comment by merdok** [comment]
Version 0.9.2 should now have initial dmaker fan support. Could you guys try it out and also post your debug log after connecting to the fan?

**Comment by sw2719** [comment]
After testing:
Fan control (Turning fan on/off, Swing mode, Natural wind, Child lock) works.
Buzzer/LED control and turning left or right doesn't work.
Fan behaves weirdly when switching buzzer on from HomeKit. After turning on buzzer and then fan, sometimes LED blinks, sometimes it turns on after a few seconds, sometimes it just doesn't do anything.

**Comment by sw2719** [comment]
After messing around a bit suddenly my fan stopped working over WiFi and I had to reset the fan to get it working. Weird.

**Comment by sw2719** [comment]
```
0|hoobs    | [Mi Fan] Xiaomi Fan - found Fan in network. Trying to connect...
0|hoobs    | [Mi Fan] Xiaomi Fan - connected to Fan
0|hoobs    | [Mi Fan] MiioDevice {
0|hoobs    |   model=dmaker.fan.p5,
0|hoobs    |   types=miio,
0|hoobs    |   capabilities=
0|hoobs    | }
0|hoobs    | [Mi Fan] Xiaomi Fan - fan model info file already exists, not saving!
0|hoobs    | Accessory refresh triggered
0|hoobs    | [Mi Fan] Dmaker fan properties:
0|hoobs    | [Mi Fan] [
0|hoobs    |   false, 'normal',
0|hoobs    |   100,   false,
0|hoobs    |   140,   0,
0|hoobs    |   true,  false,
0|hoobs    |   false, 4
0|hoobs    | ]

0|hoobs    | [Mi Fan] Xiaomi Fan - error while setting buzzer state to: true. Error: Error: Call to device timed out
0|hoobs    |     at Timeout.retry [as _onTimeout] (/root/.hoobs/node_modules/miio/lib/network.js:487:18)
0|hoobs    |     at listOnTimeout (internal/timers.js:549:17)
0|hoobs    |     at processTimers (internal/timers.js:492:7)
0|hoobs    |  {
0|hoobs    |   code: 'timeout'
0|hoobs    | }

0|hoobs    | [Mi Fan] Xiaomi Fan - error while setting led state to: true. Error: Error: Call to device timed out
0|hoobs    |     at Timeout.retry [as _onTimeout] (/root/.hoobs/node_modules/miio/lib/network.js:487:18)
0|hoobs    |     at listOnTimeout (internal/timers.js:549:17)
0|hoobs    |     at processTimers (internal/timers.js:492:7)
0|hoobs    |  {
0|hoobs    |   code: 'timeout'
0|hoobs    | }
```

My fan's LED was on, and buzzer was off. Turning left or right times out as well. Same error.

**Comment by merdok** [comment]
Yeah, only basic things should work. Buzzer, led or move will not work unless I can do some testing on the fan...

**Comment by merdok** [comment]
As of version 0.9.3 the dmaker.fan.p5 should be fully supported.
