### ISSUE TITLE
I have the latest model, but I cannot use the plugin

### ISSUE THREAD

**Issue by ssetaee** [merdok/homebridge-xiaomi-fan#8]
model：dmaker.fan.p10
log：
```
5/28/2020, 2:35:46 PM] [Xiaomi Fan 2] Xiaomi Fan - connected to Fan
[5/28/2020, 2:35:46 PM] [Xiaomi Fan 2] MiioDevice {
  model=dmaker.fan.p10,
  types=miio,
  capabilities=
}
[5/28/2020, 2:35:46 PM] [Xiaomi Fan 2] Xiaomi Fan - error occured could not write fan model info [Error: ENOENT: no such file or directory, open '~/.xiaomiFan/info_19216850118_466f849648a1bea6611f59f156b5fe36'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '~/.xiaomiFan/info_19216850118_466f849648a1bea6611f59f156b5fe36'
[5/28/2020, 2:35:49 PM] [Xiaomi Fan 2] Xiaomi Fan - error while requesting led state: Error: busy.
    at Object.reject (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:310:20)
    at UDP.onMessage (dgram.js:924:8) {
  code: -30012
}
[5/28/2020, 2:35:52 PM] [Xiaomi Fan 2] Xiaomi Fan - error while requesting power state: Error: busy.
    at Object.reject (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:310:20)
    at UDP.onMessage (dgram.js:924:8) {
  code: -30012
}
[5/28/2020, 2:35:52 PM] [Xiaomi Fan 2] Xiaomi Fan - error while requesting child lock state: Error: busy.
    at Object.reject (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:310:20)
    at UDP.onMessage (dgram.js:924:8) {
  code: -30012
}
[5/28/2020, 2:35:52 PM] [Xiaomi Fan 2] Xiaomi Fan - error while requesting speed level: Error: busy.
    at Object.reject (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:310:20)
    at UDP.onMessage (dgram.js:924:8) {
  code: -30012
}
[5/28/2020, 2:35:52 PM] [Xiaomi Fan 2] Xiaomi Fan - error while requesting mode: Error: busy.
    at Object.reject (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:310:20)
    at UDP.onMessage (dgram.js:924:8) {
  code: -30012
}
[5/28/2020, 2:35:53 PM] [Xiaomi Fan 2] Xiaomi Fan - error while requesting swing mode state: Error: busy.
    at Object.reject (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:310:20)
    at UDP.onMessage (dgram.js:924:8) {
  code: -30012
}
[5/28/2020, 2:35:56 PM] [Xiaomi Fan 2] Xiaomi Fan - Fan found
[5/28/2020, 2:36:00 PM] [Xiaomi Fan 2] Xiaomi Fan - error while requesting buzzer state: Error: Call to device timed out
    at Timeout.retry [as _onTimeout] (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:487:18)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  code: 'timeout'
}
[5/28/2020, 2:36:00 PM] [Config] Starting terminal session
[5/28/2020, 2:36:06 PM] [Xiaomi Fan 2] Xiaomi Fan - Fan found
[5/28/2020, 2:36:14 PM] [Config] [homebridge-xiaomi-fan] Failed to check registry.npmjs.org for updates: Timeout: request took more than 15 seconds
[5/28/2020, 2:36:16 PM] [Xiaomi Fan 2] Xiaomi Fan - Fan found
[5/28/2020, 2:36:26 PM] [Xiaomi Fan 2] Xiaomi Fan - Fan found
[5/28/2020, 2:36:36 PM] [Xiaomi Fan 2] Xiaomi Fan - Fan found
[5/28/2020, 2:36:46 PM] [Xiaomi Fan 2] Xiaomi Fan - Fan found
[5/28/2020, 2:36:56 PM] [Xiaomi Fan 2] Xiaomi Fan - Fan found
[5/28/2020, 2:37:06 PM] [Xiaomi Fan 2] Xiaomi Fan - Fan found
[5/28/2020, 2:37:16 PM] [Xiaomi Fan 2] Xiaomi Fan - Fan found
[5/28/2020, 2:37:26 PM] [Xiaomi Fan 2] Xiaomi Fan - Fan found
[5/28/2020, 2:37:36 PM] [Xiaomi Fan 2] Xiaomi Fan - Fan found
[5/28/2020, 2:37:46 PM] [Xiaomi Fan 2] Xiaomi Fan - Fan found
[5/28/2020, 2:37:56 PM] [Xiaomi Fan 2] Xiaomi Fan - Fan found
[5/28/2020, 2:38:06 PM] [Xiaomi Fan 2] Xiaomi Fan - Fan found
[5/28/2020, 2:38:16 PM] [Xiaomi Fan 2] Xiaomi Fan - Fan found
[5/28/2020, 2:38:26 PM] [Xiaomi Fan 2] Xiaomi Fan - Fan found
[5/28/2020, 2:38:36 PM] [Xiaomi Fan 2] Xiaomi Fan - Fan found
[5/28/2020, 2:38:46 PM] [Xiaomi Fan 2] Xiaomi Fan - Fan found
[5/28/2020, 2:38:56 PM] [Xiaomi Fan 2] Xiaomi Fan - Fan found
[5/28/2020, 2:39:06 PM] [Xiaomi Fan 2] Xiaomi Fan - Fan found
[5/28/2020, 2:39:16 PM] [Xiaomi Fan 2] Xiaomi Fan - Fan found
```

**Comment by merdok** [comment]
You might have some permissions errors with homebridge, since the plugin is not able to write the info file.

**Comment by ssetaee** [comment]
What can I do? Capture packets to get the device's transmission commands to help adapt to the new model

**Comment by merdok** [comment]
Recheck your homebridge setup. Maybe try to reinstall homebridge.

**Comment by merdok** [comment]
@8lele
Version 0.9.2 should now have initial dmaker fan support. Could you try it out and also post your debug log after connecting to the fan?

**Comment by ssetaee** [comment]
@merdok 
debug log
```
[6/25/2020, 2:11:44 AM] [Xiaomi Fan 2] Xiaomi Fan - found Fan in network. Trying to connect...
[6/25/2020, 2:11:44 AM] [Xiaomi Fan 2] Xiaomi Fan - connected to Fan
[6/25/2020, 2:11:44 AM] [Xiaomi Fan 2] MiioDevice {
  model=dmaker.fan.p10,
  types=miio,
  capabilities=
}
[6/25/2020, 2:11:44 AM] [Xiaomi Fan 2] Xiaomi Fan - fan model info file already exists, not saving!
[6/25/2020, 2:11:54 AM] [Config] [homebridge] Failed to check registry.npmjs.org for updates: timeout of 5000ms exceeded
[6/25/2020, 2:11:56 AM] [Xiaomi Fan 2] Xiaomi Fan - error while requesting dmaker fan properties: Error: Call to device timed out
    at Timeout.retry [as _onTimeout] (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:487:18)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  code: 'timeout'
}
[6/25/2020, 2:12:07 AM] [Config] Terminal session ended.
[6/25/2020, 2:12:13 AM] [XiaoMiAcPartner] [DEBUG]FastSync...
[6/25/2020, 2:12:15 AM] [Xiaomi Fan 2] Xiaomi Fan - error while requesting child lock state: Error: busy.
    at Object.reject (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:310:20)
    at UDP.onMessage (dgram.js:924:8) {
  code: -30012
}
[6/25/2020, 2:12:15 AM] [Xiaomi Fan 2] Xiaomi Fan - error while requesting swing mode state: Error: busy.
    at Object.reject (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:310:20)
    at UDP.onMessage (dgram.js:924:8) {
  code: -30012
}
[6/25/2020, 2:12:15 AM] [Xiaomi Fan 2] Xiaomi Fan - error while requesting power state: Error: busy.
    at Object.reject (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:310:20)
    at UDP.onMessage (dgram.js:924:8) {
  code: -30012
}
[6/25/2020, 2:12:15 AM] [Xiaomi Fan 2] Xiaomi Fan - error while requesting speed level: Error: busy.
    at Object.reject (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:310:20)
    at UDP.onMessage (dgram.js:924:8) {
  code: -30012
}
[6/25/2020, 2:12:15 AM] [Xiaomi Fan 2] Xiaomi Fan - error while requesting mode: Error: busy.
    at Object.reject (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:310:20)
    at UDP.onMessage (dgram.js:924:8) {
  code: -30012
}
[6/25/2020, 2:12:15 AM] [Xiaomi Fan 2] Xiaomi Fan - error while requesting buzzer state: Error: busy.
    at Object.reject (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:310:20)
    at UDP.onMessage (dgram.js:924:8) {
  code: -30012
}
[6/25/2020, 2:12:17 AM] [Xiaomi Fan 2] Xiaomi Fan - error while setting speed level to: 38. Error: Error: busy.
    at Object.reject (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:310:20)
    at UDP.onMessage (dgram.js:924:8) {
  code: -30012
}
[6/25/2020, 2:12:17 AM] [Xiaomi Fan 2] Xiaomi Fan - error while setting power state to: true. Error: Error: busy.
    at Object.reject (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:310:20)
    at UDP.onMessage (dgram.js:924:8) {
  code: -30012
}
[6/25/2020, 2:12:19 AM] [Xiaomi Fan 2] Xiaomi Fan - error while setting power state to: true. Error: Error: busy.
    at Object.reject (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:310:20)
    at UDP.onMessage (dgram.js:924:8) {
  code: -30012
}
[6/25/2020, 2:12:19 AM] [Xiaomi Fan 2] Xiaomi Fan - error while setting buzzer state to: true. Error: Error: busy.
    at Object.reject (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:310:20)
    at UDP.onMessage (dgram.js:924:8) {
  code: -30012
}
[6/25/2020, 2:12:19 AM] [Xiaomi Fan 2] Xiaomi Fan - error while setting speed level to: 62. Error: Error: busy.
    at Object.reject (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:310:20)
    at UDP.onMessage (dgram.js:924:8) {
  code: -30012
}
[6/25/2020, 2:12:19 AM] [Xiaomi Fan 2] Xiaomi Fan - error while setting power state to: true. Error: Error: busy.
    at Object.reject (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:310:20)
    at UDP.onMessage (dgram.js:924:8) {
  code: -30012
}
[6/25/2020, 2:12:20 AM] [Xiaomi Fan 2] Xiaomi Fan - error while setting speed level to: 98. Error: Error: busy.
    at Object.reject (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:310:20)
    at UDP.onMessage (dgram.js:924:8) {
  code: -30012
}
[6/25/2020, 2:12:20 AM] [Xiaomi Fan 2] Xiaomi Fan - error while setting power state to: true. Error: Error: busy.
    at Object.reject (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:310:20)
    at UDP.onMessage (dgram.js:924:8) {
  code: -30012
}
[6/25/2020, 2:12:20 AM] [Xiaomi Fan 2] Xiaomi Fan - error while setting speed level to: 100. Error: Error: busy.
    at Object.reject (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:310:20)
    at UDP.onMessage (dgram.js:924:8) {
  code: -30012
}
[6/25/2020, 2:12:20 AM] [Xiaomi Fan 2] Xiaomi Fan - fan move service - direction: left
[6/25/2020, 2:12:20 AM] [Xiaomi Fan 2] Xiaomi Fan - fan move service - error moving fan to: left. Error: Error: busy.
    at Object.reject (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:310:20)
    at UDP.onMessage (dgram.js:924:8) {
  code: -30012
}
[6/25/2020, 2:12:21 AM] [Xiaomi Fan 2] Xiaomi Fan - fan move service - direction: right
[6/25/2020, 2:12:21 AM] [Xiaomi Fan 2] Xiaomi Fan - fan move service - error moving fan to: right. Error: Error: busy.
    at Object.reject (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:310:20)
    at UDP.onMessage (dgram.js:924:8) {
  code: -30012
}
[6/25/2020, 2:12:21 AM] [Xiaomi Fan 2] Xiaomi Fan - error while setting speed level to: 55. Error: Error: busy.
    at Object.reject (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:310:20)
    at UDP.onMessage (dgram.js:924:8) {
  code: -30012
}
[6/25/2020, 2:12:21 AM] [Xiaomi Fan 2] Xiaomi Fan - fan move service - direction: left
[6/25/2020, 2:12:21 AM] [Xiaomi Fan 2] Xiaomi Fan - fan move service - error moving fan to: left. Error: Error: busy.
    at Object.reject (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-xiaomi-fan/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:310:20)
    at UDP.onMessage (dgram.js:924:8) {
  code: -30012
}
```

**Comment by merdok** [comment]
Do you have version 0.9.2 installed?

**Comment by ssetaee** [comment]
![image.png](https://i.loli.net/2020/06/25/KRxepylWktsQIOL.png)
This is the 0.9.2 version I installed.

**Comment by merdok** [comment]
If you want me to add support for your fan then you would need to dump the commands from your fan. Would you willing to do that?

**Comment by ssetaee** [comment]
How can I assist you in obtaining information?
What software tools do I need to use?

**Comment by merdok** [comment]
It requires a a couple of steps to be done. You can basically read here how to dump commands from your device:
https://github.com/aholstenson/miio/blob/master/docs/protocol.md
https://github.com/jghaanstra/com.robot.xiaomi-mi

**Comment by ssetaee** [comment]
<a href="https://sm.ms/image/gCcKXzofpndR3JU" target="_blank"><img src="https://i.loli.net/2020/06/28/gCcKXzofpndR3JU.png" ></a>

After my attempt, the new fan cannot obtain the transmission protocol through Wireshark, and the fan button of the home app is operated. Wireshark does not display any traffic changes.

**Comment by merdok** [comment]
I think that you have to disconnect the internet in order that the commands are send using the local network instead of the cloud.

**Comment by ssetaee** [comment]
<a href="https://sm.ms/image/yEm3nWLuoxpwZNX" target="_blank"><img src="https://i.loli.net/2020/06/28/yEm3nWLuoxpwZNX.png" ></a>

If I disconnect the internet connection, then I can’t do anything in the home app, nor can I get any traffic information
I think it is the new version of the app that adjusts the access method of the device. When I try to use the old version of the app and it is not compatible with the new device, a problem

**Comment by merdok** [comment]
This is unfortunately a problem. We somehow need to catch the commands which the app sends to the fan in order for me to implement the fan...

**Comment by sw2719** [comment]
Could you try to log the commands with modded mi home app?  [Follow this gude.](https://gist.github.com/sw2719/fe7820e1913fc876f9011700b31ae625)

**Comment by ssetaee** [comment]
@sw2719 Thanks for the tutorial，After trying to get the switch command
This is the command to get the ‮  status

```
2020-07-26 19:14:46 -> {"id":5502,"method":"get_properties","params":[{"did":"239246709","siid":2,"piid":1},{"did":"239246709","siid":2,"piid":3},{"did":"239246709","siid":2,"piid":10},{"did":"239246709","siid":2,"piid":4},{"did":"239246709","siid":2,"piid":5},{"did":"239246709","siid":2,"piid":6},{"did":"239246709","siid":2,"piid":7},{"did":"239246709","siid":2,"piid":8},{"did":"239246709","siid":3,"piid":1}]}
2020-07-26 19:14:46 <- {"code":0,"message":"ok","result":[{"did":"239246709","siid":2,"piid":1,"code":0,"value":true},{"did":"239246709","siid":2,"piid":3,"code":0,"value":0},{"did":"239246709","siid":2,"piid":10,"code":0,"value":100},{"did":"239246709","siid":2,"piid":4,"code":0,"value":false},{"did":"239246709","siid":2,"piid":5,"code":0,"value":90},{"did":"239246709","siid":2,"piid":6,"code":0,"value":0},{"did":"239246709","siid":2,"piid":7,"code":0,"value":true},{"did":"239246709","siid":2,"piid":8,"code":0,"value":true},{"did":"239246709","siid":3,"piid":1,"code":0,"value":false}],"id":5502}
```
This is the shutdown command

```2020-07-26 19:15:19 -> {"params":[{"did":"239246709","siid":2,"piid":1,"value":false}]} /miotspec/prop/set
2020-07-26 19:15:19 <- {"code":0,"message":"","result":[{"did":"239246709","siid":2,"piid":1,"code":0}]}
```

This is the boot command   

```
2020-07-26 19:15:22 -> {"params":[{"did":"239246709","siid":2,"piid":1,"value":true}]} /miotspec/prop/set
2020-07-26 19:15:22 <- {"code":0,"message":"","result":[{"did":"239246709","siid":2,"piid":1,"code":0}]}
```

@merdok You can see if these logs can help you achieve access

**Comment by merdok** [comment]
@8lele thanks! I think that is really helpful, i think i will release an update later today which will add initial support for your fan.

**Comment by merdok** [comment]
@8lele can you try version 1.2.0. It has no full support for your fan yet, but at least you should be able to do some controls now.

**Comment by ssetaee** [comment]
![image.png](https://i.loli.net/2020/07/26/7i8jTGhMe5s9lCv.png)

There was a problem that could not be installed

**Comment by merdok** [comment]
@8lele i think this is some issue with your connection?

**Comment by ssetaee** [comment]
@merdok After trying, you can control the fan switch speed，I try to provide all command signals of the device
thinks

**Comment by merdok** [comment]
Oh, does it at least partialy work? Can you tell what works?

**Comment by ssetaee** [comment]
Functions that can be manipulated
1. The wind speed can be reduced
2. The fan can be turned off
3. You can switch between natural wind and direct wind
The problem
1. The fan cannot be turned on directly,
2. The fan has 100-level wind speed and cannot be switched freely

**Comment by merdok** [comment]
Ok, that sounds good that some stuff is already working. I will be now working to update the plugin to fully support your device! Thanks for the testing!

**Comment by ssetaee** [comment]
If necessary, I will provide more commands to help you improve the plug-in.

**Comment by merdok** [comment]
@8lele version 1.3.0 should add support for the dmaker.fan.p10. Can you try it out please?

**Comment by ssetaee** [comment]
@merdok 
After I control by Mijia, the home app cannot be automatically updated to get the latest status of the fan

**Comment by merdok** [comment]
I think after that you need to restart the fan in order to control again in the home app. This is an issue with the fan itself.
