### ISSUE TITLE
user ack timeout

### ISSUE THREAD

**Issue by vskal** [merdok/homebridge-xiaomi-fan#83]
@merdok Thank you for the great work !

I have installed the plugin for a SmartMi Fan 2 with no problems, device appears in Homekit and Homebridge reports no errors (It reports that the device is connected). However I cannot control it.

The following is the relevant part of my debug log. 
The only thing I could see id the "usr ack timeout" which looks like a communication problem.

Could this be related to the plugin ?

2021-04-20T12:00:19.927Z thing:miio:106610149 -> (4) {"method":"get_properties","params":[{"did":"106610149","siid":2,"piid":1},{"did":"106610149","siid":2,"piid":2},{"did":"106610149","siid":3,"piid":1},{"did":"106610149","siid":2,"piid":3},{"did":"106610149","siid":2,"piid":5},{"did":"106610149","siid":2,"piid":7},{"did":"106610149","siid":2,"piid":10},{"did":"106610149","siid":4,"piid":3},{"did":"106610149","siid":5,"piid":1}],"id":3515}
2021-04-20T12:00:19.927Z miio:packet -> <Buffer 21 31 01 b0 00 00 00 00 06 5a bd e5 00 00 10 06 d6 f1 cf b1 e8 40 40 4e 2f 5e 23 72 75 be 0b 7b>
2021-04-20T12:00:19.929Z miio:network Grabbing reference to network
2021-04-20T12:00:19.929Z thing:miio:106610149 Using manual token: XXXXXXXXXXXXXXXXXXXXXXXXX
2021-04-20T12:00:19.929Z miio:network Releasing reference to network
2021-04-20T12:00:19.929Z thing:miio:106610149 -> (5) {"method":"miIO.info","params":[],"id":3516}
2021-04-20T12:00:19.929Z miio:packet -> <Buffer 21 31 00 50 00 00 00 00 06 5a bd e5 00 00 10 06 9b 82 f9 d3 f7 61 32 ba 29 7f 8d 61 36 1c 36 87>
2021-04-20T12:00:20.040Z miio:packet <- <Buffer 21 31 00 60 00 00 00 00 06 5a bd e5 00 00 10 07 d7 c9 04 d1 34 34 1a ed 62 c8 ed b0 4d 8c 44 49>
2021-04-20T12:00:20.041Z miio:packet <- <Buffer 21 31 00 60 00 00 00 00 06 5a bd e5 00 00 10 07 d7 c9 04 d1 34 34 1a ed 62 c8 ed b0 4d 8c 44 49>
2021-04-20T12:00:20.041Z thing:miio:106610149 <- Message: `{"id":3214,"error":{"code":-9999,"message":"user ack timeout"}}`
2021-04-20T12:00:20.116Z miio:packet <- <Buffer 21 31 01 f0 00 00 00 00 06 5a bd e5 00 00 10 07 0d 6f 20 37 9e 00 26 a0 e2 2d 4c ae 11 e9 60 0f>
2021-04-20T12:00:20.116Z miio:packet <- <Buffer 21 31 01 f0 00 00 00 00 06 5a bd e5 00 00 10 07 0d 6f 20 37 9e 00 26 a0 e2 2d 4c ae 11 e9 60 0f>
2021-04-20T12:00:20.116Z thing:miio:106610149 <- Message: `{"id":3516,"result":{"life":4103,"uid":6398847950,"model":"zhimi.fan.za3","token":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","fw_ver":"2.0.3","mcu_fw_ver":"0013","miio_ver":"0.0.3","hw_ver":"esp32","mmfree":68008,"mac":"40:31:3C:44:51:87","wifi_fw_ver":"v3.1.3-8-gce4d3fe10","ap":{"rssi":-42,"ssid":"XXXXXXXXXX","primary":3,"bssid":"3C:7C:3F:F6:EB:A0"},"netif":{"localIp":"192.168.1.219","mask":"255.255.255.0","gw":"192.168.1.1"},"miio_times":[4102,3,3,4096]}}`
2021-04-20T12:00:20.116Z miio:network Grabbing reference to network
2021-04-20T12:00:20.116Z miio:network Releasing reference to network
[4/20/2021, 3:00:20 PM] [xiaomifan] [Mi Fan] Connected to Fan zhimi.fan.za3
2021-04-20T12:00:20.117Z thing:miio:106610149 -> (5) {"method":"miIO.info","params":[],"id":3517}
2021-04-20T12:00:20.117Z miio:packet -> <Buffer 21 31 00 50 00 00 00 00 06 5a bd e5 00 00 10 07 4b fe cc d4 6c 08 41 fc f2 2b 06 d4 4c 76 b6 26>
2021-04-20T12:00:20.118Z thing:miio:106610149 -> (5) {"method":"get_properties","params":[{"did":"106610149","siid":2,"piid":1},{"did":"106610149","siid":2,"piid":2},{"did":"106610149","siid":3,"piid":1},{"did":"106610149","siid":2,"piid":3},{"did":"106610149","siid":2,"piid":5},{"did":"106610149","siid":2,"piid":7},{"did":"106610149","siid":2,"piid":10},{"did":"106610149","siid":4,"piid":3},{"did":"106610149","siid":5,"piid":1}],"id":3518}
2021-04-20T12:00:20.118Z miio:packet -> <Buffer 21 31 01 b0 00 00 00 00 06 5a bd e5 00 00 10 07 a5 cd 00 89 fb cf 1c f0 51 73 6b 65 75 2d 00 40>
2021-04-20T12:00:20.133Z miio:packet <- <Buffer 21 31 01 f0 00 00 00 00 06 5a bd e5 00 00 10 07 4d 41 10 58 5a f6 14 20 91 0f 43 45 4e c1 ac 04>
2021-04-20T12:00:20.133Z miio:packet <- <Buffer 21 31 01 f0 00 00 00 00 06 5a bd e5 00 00 10 07 4d 41 10 58 5a f6 14 20 91 0f 43 45 4e c1 ac 04>
2021-04-20T12:00:20.133Z thing:miio:106610149 <- Message: `{"id":3517,"result":{"life":4103,"uid":6398847950,"model":"zhimi.fan.za3","token":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","fw_ver":"2.0.3","mcu_fw_ver":"0013","miio_ver":"0.0.3","hw_ver":"esp32","mmfree":67504,"mac":"40:31:3C:44:51:87","wifi_fw_ver":"v3.1.3-8-gce4d3fe10","ap":{"rssi":-42,"ssid":"XXXXXXXXXXXXX","primary":3,"bssid":"3C:7C:3F:F6:EB:A0"},"netif":{"localIp":"192.168.1.219","mask":"255.255.255.0","gw":"192.168.1.1"},"miio_times":[4102,3,3,4096]}}`
2021-04-20T12:00:20.929Z thing:miio:106610149 -> (1) {"method":"get_properties","params":[{"did":"106610149","siid":2,"piid":1},{"did":"106610149","siid":2,"piid":2},{"did":"106610149","siid":3,"piid":1},{"did":"106610149","siid":2,"piid":3},{"did":"106610149","siid":2,"piid":5},{"did":"106610149","siid":2,"piid":7},{"did":"106610149","siid":2,"piid":10},{"did":"106610149","siid":4,"piid":3},{"did":"106610149","siid":5,"piid":1}],"id":3618}
2021-04-20T12:00:20.929Z miio:packet -> <Buffer 21 31 01 b0 00 00 00 00 06 5a bd e5 00 00 10 07 6f 54 47 55 d6 b4 69 a9 16 79 ae f9 6b b3 12 4c>
2021-04-20T12:00:20.961Z miio:packet <- <Buffer 21 31 00 60 00 00 00 00 06 5a bd e5 00 00 10 08 63 37 f2 e9 b8 e0 94 37 d2 f5 8d 71 1e 45 39 92>
2021-04-20T12:00:20.961Z miio:packet <- <Buffer 21 31 00 60 00 00 00 00 06 5a bd e5 00 00 10 08 63 37 f2 e9 b8 e0 94 37 d2 f5 8d 71 1e 45 39 92>

**Comment by vskal** [comment]
This is the log when trying to change the speed:

2021-04-20T13:18:31.552Z HAP-NodeJS:Characteristic [Rotation Speed] Received error from set handler Error: [Mi Fan] Fan is not connected, cannot set rotation speed
    at xiaomiFanDevice.createError (/homebridge/node_modules/homebridge-xiaomi-fan/index.js:918:12)
    at xiaomiFanDevice.setRotationSpeed (/homebridge/node_modules/homebridge-xiaomi-fan/index.js:540:21)
    at RotationSpeed.emit (events.js:315:20)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1632:16
    at new Promise (<anonymous>)
    at RotationSpeed.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1630:14)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)

trying to set fan level:
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
2021-04-20T14:13:56.589Z HAP-NodeJS:Accessory [Homebridge 3202 ED58] Error setting Characteristic "On" to value 1:  SERVICE_COMMUNICATION_FAILURE
2021-04-20T14:13:56.589Z HAP-NodeJS:EventedHTTPServer:Connection [::ffff:192.168.1.35] HTTP Response is finished
2021-04-20T14:13:56.680Z thing:miio:106610149 -> (2) {"method":"miIO.info","params":[],"id":1804}
2021-04-20T14:13:56.680Z miio:packet -> <Buffer 21 31 00 50 00 00 00 00 06 5a bd e5 00 00 01 cc 98 ed 41 2b b4 d4 19 d3 f7 5d b7 0f d8 70 b7 ee>
2021-04-20T14:13:58.085Z ciao:Responder Sending response via unicast to {"address":"192.168.1.17","port":5353,"interface":"br0"} (took 3 ms): [PTR,PTR,PTR] answers and [TXT,SRV,A,NSEC,NSEC,TXT,SRV,A,NSEC,NSEC,TXT,SRV,A,NSEC,NSEC] additionals with size 806B (UPS: 1440)
2021-04-20T14:13:58.681Z thing:miio:106610149 -> (1) {"method":"miIO.info","params":[],"id":1904}
2021-04-20T14:13:58.681Z miio:packet -> <Buffer 21 31 00 50 00 00 00 00 06 5a bd e5 00 00 01 ce bb 81 a9 3d b4 2f a3 89 c6 a5 7a 50 7f b1 f4 54>
2021-04-20T14:14:00.682Z thing:miio:106610149 -> (0) {"method":"miIO.info","params":[],"id":2004}
2021-04-20T14:14:00.682Z miio:packet -> <Buffer 21 31 00 50 00 00 00 00 06 5a bd e5 00 00 01 d0 62 bf e1 71 c3 64 6e 59 2d da b9 1a 36 ce 46 20>
2021-04-20T14:14:02.683Z miio:network Releasing reference to network
2021-04-20T14:14:02.683Z miio:network Network no longer active, destroying socket

**Comment by merdok** [comment]
Can you show me your config? Are you sure that the fan ip address and token are correct?

**Comment by vskal** [comment]
Sure, many thanks !

The IP is correct, have set it to static IP from router.
I am quite sure I have got the token correct because I have 4 more Mi devices working correctly with their tokens extracted with iOS backup and dbase sql.

I have tried uninstalling the plugin and also resetting the device. Had to get a new token for that but still no communication I am afraid.
            "devices": [
                {
                    "name": "My Xiaomi Fan",
                    "ip": "192.168.1.219",
                    "token": "1e435d8b9f3e3fb2e7a789d0ff2b5b7c",
                    "model": "SmartMi Standing Fan 2",
                    "pollingInterval": 5,
                    "buzzerControl": true,
                    "ledControl": true,
                    "naturalModeControl": true,
                    "sleepModeControl": true,
                    "moveControl": false,
                    "shutdownTimer": false,
                    "ioniserControl": false
                }
            ],
            "platform": "xiaomifan"

**Comment by merdok** [comment]
You should not specify the model property if you do not know what device model your device is. From the logs i see that your model is `zhimi.fan.za3` which is completely different then what you specified there. So you should put there `zhimi.fan.za3` or leave it empty.

**Comment by vskal** [comment]
Yes that did it, how did I miss that.
Sorry for the issue and many thanks for the fast solution.

The plugin rocks !
